---
title: "Evaluate stan time varying effects (tve) piecewise models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages

library(tidyverse)
library(rstanarm)
library(loo)
library(brms)
options(mc.cores = parallel::detectCores())
library(cowplot)
library(bayesplot)
#theme_set(bayesplot::theme_default())
theme_set(bayesplot::theme_default(base_family = "sans"))

```

# Models

```{r}

mod1.pw5 <- readRDS("../processed/mod1_pecewise5.rds")
mod1.pw10 <- readRDS("../processed/mod1_pecewise10.rds")

loo_mod1_pw5 <- readRDS("../processed/loo_mod1_pw5.rds")
loo_mod1_pw10 <- readRDS("../processed/loo_mod1_pw10.rds")

loo_wt_pw <- readRDS("../processed/loo_wt_pw.rds")

```

# Examine posteriors

```{r}
# Inspect the marginal prior distributions for log HR for treatment
# (aka Central posterior uncertainty intervals)
# The default is to show 50% intervals (the thick segments) and 90% intervals (the thinner outer lines). These defaults can be changed using the prob and prob_outer arguments, respectively. Points in the plot are posterior medians.
color_scheme_set("red")
mcmc_intervals(mod1, pars = c(
  "larvalTreatDR","adultTreatDR","sexM","(Intercept)")
  )

# Uncertainty intervals as shaded areas under the estimated posterior density curves
color_scheme_set("red")
mcmc_areas(mod1, 
           pars=c("larvalTreatDR","adultTreatDR","sexM"),
           prob=0.8,prob_outer = .999,point_est = "mean")
# Some marginals significantly away from zero

# Change to a mixed color scheme to see differences between chains 
color_scheme_set("mix-blue-red")
mcmc_trace(mod1, pars = c("larvalTreatDR","adultTreatDR","sexM"), 
           facet_args = list(ncol = 1, strip.position = "left"))

# Use points instead of lines and highlight one chain
mcmc_trace_highlight(mod1, pars = "larvalTreatDR", highlight = 3)

```

# LOO weights

```{r}
lpd1 <- loo(log_lik_list[[1]], r_eff = r_eff_list[[1]])$pointwise[,1]
# Basic model (larval, adult, sex)
loo_0 <- readRDS("../processed/loo_0.rds")

# Basic model (tve)
loo_1 <- readRDS("../processed/loo_1.rds")

# B_splines model
loo_2 <- readRDS("../processed/loo_2.rds")


# stacking weights
loo_list <- list(list(mod0, mod1, mod1_bspline))


wts <- loo::loo_model_weights(mod_list, 
                              method = "pseudobma")
print(wts)

```


# Model comparison

```{r}
loop_basic <- readRDS("../processed/loop_basic.rds") #mod0 vs mod1
mods <- readRDS("../processed/loop.rds")
loop_comp <- readRDS("../processed/loop_compare.rds")
plot(loop_comp)

loop <- readRDS("../processed/loop.rds")
plot(loop)
loop_ex <- readRDS("../processed/loop_exp.rds")
plot(loop_ex)
loop_wb <- readRDS("../processed/loop_weibull.rds")
plot(loop_wb)
loop_gp <- readRDS("../processed/loop_gompertz.rds")
plot(loop_gp) # looks better than rest
loop_bs <- readRDS("../processed/loop_bspline.rds")
plot(loop_bs) 
loop_ms <- readRDS("../processed/loop_mspline1.rds")
plot(loop_ms)
loop_mp <- readRDS("../processed/loop_mspline2.rds")
plot(loop_mp)

mcmc_areas(as.matrix(mod1_exp), prob_outer = .999)
mcmc_areas(as.matrix(mod1_weibull), prob_outer = .999)

```

# Plot basic model (mod1) for some survival distributions

```{r}
# Plot the baseline hazards with 95% posterior uncertainty limits
# load("../processed/BaseHaz.Rda")

plotfun <- function(model, title) {
  plot(model, plotfun = "basehaz") +              
    coord_cartesian(ylim = c(0,0.4)) +            
    labs(title = title) +                        
    theme(plot.title = element_text(hjust = 0.5,size = 10),
          axis.title = element_text(size = 9)) + 
    theme_set(theme_cowplot()) +
    theme_half_open() 
}
p_exp      <- plotfun(mod1_exp,      title = "Exponential")
p_weibull  <- plotfun(mod1_weibull,  title = "Weibull")
p_gompertz <- plotfun(mod1_gompertz, title = "Gompertz")
p_bspline  <- plotfun(mod1_bspline,  title = "B-splines with df = 5")
p_mspline1 <- plotfun(mod1_mspline1, title = "M-splines with df = 5")
p_mspline2 <- plotfun(mod1_mspline2, title = "M-splines with df = 10")
cs <-bayesplot::bayesplot_grid(p_exp,
                               p_weibull,
                               p_gompertz,
                               p_bspline,
                               p_mspline1,
                               p_mspline2,
                               grid_args = list(ncol = 3))

ggplot2::ggsave(cs,filename="../plots/baseHaz_tve_fixedEffs_new1.pdf",height = 6, width=10)

mm.sum <- summary(mod1_mspline2)
mm.post <- posterior_survfit(mod1_mspline2)
mm.plot <- plot(mmp)

save(mm.sum,mm.post,mm.plot, file="../processed/bhaz_mm.Rda")

```

# Prior vs posterior checks for mod1

```{r}
plot_grid(
  
bayesplot_grid(mcmc_intervals(mod1),
               mcmc_intervals(mod1_mspline2),
               titles = c("Prior", "Posterior"), 
               xlim = c(-2, 1),
               grid_args = list(ncol = 2)),

bayesplot_grid(mcmc_hist(mod1), 
               mcmc_hist(mod1_mspline2),
               titles = c("Prior", "Posterior"), 
               grid_args = list(nrow = 2)),
ncol = 2 )


```

# Plot the best model

```{r}
loop1 <- loo(mod1)
plot(mod1, plotfun = "tve",pars = "larvalTreatDR")
plot(mod1, plotfun = "tve",pars = "adultTreatDR")
plot(mod1, plotfun = "tve",pars = "sexM")
mcmc_intervals(mod1,"tve", pars="larvalTreatDR","adultTreatDR","sexM")

# Predicted survival function (posterior median and 95% uncertainty limits) 
  # for an individual in either the DR, or C treatment group.
nd <- data.frame(larvalTreat = c("DR","DR","DR","DR","C","C","C","C"),
                 adultTreat=c("DR","DR","C","C","DR","DR","C","C"),
                 sex=c("F","M","F","M","F","M","F","M"))

psf <- posterior_survfit(mod1, newdata = nd, times = 0, extrapolate = TRUE)
head(psf)

panel_labels <- c('1' = "DR_DR_F",
                 '2' = "DR_DR_M",
                 '3' = "DR_C_F",
                 '4' = "DR_C_M",
                 '5' = "C_DR_F",
                 '6' = "C_DR_M",
                 '7' = "C_C_F",
                 '8' = "C_C_M") 

# Plot survival predictions
pps <- plot(psf) +
  facet_wrap(~ id, labeller = labeller(id = panel_labels))
pps

# Also look at he predicted hazard or log hazard functions
ph <- posterior_survfit(mod1, newdata = nd, type = "haz")
pl <- posterior_survfit(mod1, newdata = nd, type = "loghaz")

pph <- plot(ph) + 
  facet_wrap(~ id, labeller = labeller(id = panel_labels))
ppl <- plot(pl) +
  facet_wrap(~ id, labeller = labeller(id = panel_labels))

# Compare the two basic models (mod0 & mod1)
loop_basic <- loo_compare(loo(mod0),
                          loo(mod1)) # Better of the two
saveRDS(loop_basic, file="../processed/loop_basic.rds")

loop_pick <- loo_compare(loo(mod1),
                          loo(mod1_bspline))

saveRDS(loop_pick, file="../processed/loop_pick.rds")
```

# Model weights

```{r}
best_list <- stanreg_list(mod0, mod1, mod1_bspline)
loo_wts <- loo_model_weights(best_list,cores=getOption("mc.cores",4))
loo_wt <- loo_model_weights(best_list,cores=getOption("mc.cores",4))
saveRDS(loo_wts, file="../processed/loo_wts_BasicMods.rds")
```

