---
title: "The Cox model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(survminer)
library(coxme)
library(coxphw)
library(splines) 
library(tidyverse) 
library(forcats)
library(car)
library(broom)
library(AICcmodavg)
```

# Data

```{r}
eelife <- read.csv("../processed/eeAlldat.csv") %>%
  select(-X,cageID,larv_adult,larvalTreat,adultTreat,age,status,sex) 

# cols <- c("cageID", "larv_adult", "larvalTreat", "adultTreat","sex")
# eelife[cols] <- lapply(eelife[cols], factor)  
eelife$age <- as.numeric(eelife$age)
eelife$status <- as.numeric(eelife$status)
# sapply(eelife, class)


eelifeF <- eelife %>%
  filter(sex=="F")


eelifeM <- eelife %>%
  filter(sex=="M")

```


```{r}
mf1 <- coxph(Surv(age, status) ~ larv_adult * strata(sex) + cageID, eelife)
summary(mf1)
cox.zph(mf1)

mf2 <- coxph(Surv(age, status) ~ larv_adult * strata(sex), eelife)
summary(mf2)
cox.zph(mf2)

mf3 <- coxph(Surv(age, status) ~ larv_adult + cageID, eelife)
summary(mf3)
cox.zph(mf3)

mf4 <- coxph(Surv(age, status) ~ larv_adult + strata(sex), eelife)
summary(mf4)
cox.zph(mf4)

mf5 <- coxph(Surv(age, status) ~ larv_adult + strata(sex) + cageID, eelife)
summary(mf5)
cox.zph(mf5)

mf6 <- coxph(Surv(age, status) ~ larv_adult, eelife)
summary(mf6)
cox.zph(mf6)

aictab(list(mf1,mf2,mf3,mf4,mf5,mf6))
anova(mf1,mf2,mf3,mf4,mf5,mf6)
anova(mf5,mf4)
```


