---
title: "The Cox model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(survminer)
library(coxme)
library(splines) 
library(tidyverse) 
library(forcats)
library(car)
library(broom)

```

# Data

```{r}
eelife <- read.csv("../processed/eeAlldat.csv") %>%
  select(-X,cageID,larv_adult,larvalTreat,adultTreat,age,status,sex) 

# cols <- c("cageID", "larv_adult", "larvalTreat", "adultTreat","sex")
# eelife[cols] <- lapply(eelife[cols], factor)  
eelife$age <- as.numeric(eelife$age)
# sapply(eelife, class)


```

# Assuming interaction effects only:

```{r}
cxph1.1 <- coxph(Surv(age, status) ~  larvalTreat*adultTreat + sex, 
                 data = eelife)
summary(cxph1.1) # some interaction effect
cox.zph(cxph1.1)
ggforest(cxph1.1, data = eelife)
# All terms come out sig, including larval effects, and interaction effects
# Only adult diet passes PH test
```

# Assuming additive and interaction effects:

```{r}
cxph1.2.0 <- coxph(Surv(age, status) ~ larvalTreat + adultTreat + sex + 
                     larvalTreat*adultTreat, 
                   data = eelife)
summary(cxph1.2.0)
cox.zph(cxph1.2.0)
par(mfrow=c(2,2))
plot(cox.zph(cxph1.2.0))
# Identical results as cxph1.1 above
# So, running just an interaction is equivalent to adding additives
```

# Stratified regression to address non-PH condition:

Addressing non-proportional hazards: https://cran.r-project.org/web/packages/Greg/vignettes/timeSplitter.html
vignette("timedep", package = "survival")

```{r}
cxph1.2.1 <- coxph(Surv(age, status) ~ larvalTreat + adultTreat + 
                     larvalTreat*adultTreat + 
                     strata(sex), data = eelife)
summary(cxph1.2.1)
cox.zph(cxph1.2.1)
#ggforest(cxph1.2, data = eelife) #undefined columns (strata??)
# Robust effect of adult diet, larval diet nsig
extractAIC(cxph1.2.1)
tidy(cxph1.2.1,exponentiate = TRUE)
glance(cxph1.2.1)
plot(survfit(cxph1.2.1, transform="km", global=TRUE))
plot(cox.zph(cxph1.2.1,transform="km", global=TRUE))
# All terms are sig if sex is stratified
# PHs look good, although somewhat marginal for larval and interaction effects
```

# Effect of cage

```{r}
cxph1.2.2 <- coxph(Surv(age, status) ~ larvalTreat + adultTreat + cageID +
                     larvalTreat*adultTreat + 
                     strata(sex), data = eelife)
summary(cxph1.2.2) # 2 cages have sig cage effects
anova(cxph1.2.2)
cox.zph(cxph1.2.2) # cageID NPH
extractAIC(cxph1.2.2)
tidy(cxph1.2.2,exponentiate = TRUE)
glance(cxph1.2.2)
# Diet effects disappear when cage is accounted for; larval diet sig at p = 0.1
# Cage effects are sig for C_DR2 and DR_DR1 (both p = 0.001)
# CageID fails PH test

anova(cxph1.1,cxph1.2.1,cxph1.2.2)

```

## cageID as random effect

```{r}
eelife$status <- as.numeric(eelife$status)
stem(table(eelife$cageID))

cph2.1 <- coxme(Surv(age, status) ~ larvalTreat + adultTreat + 
                  larvalTreat*adultTreat + strata(sex) +
                  (1 | cageID), 
                  data = eelife)
summary(cph2.1)
car::Anova(cph2.1, type="II")
# Only adult diet is sig in the fixed effects



cph2.2 <- coxme(Surv(age, status) ~ larv_adult + strata(sex) +
                (1 | cageID), 
                data = eelife)
summary(cph2.2)
car::Anova(cph2.2, type="III")


cph2.3 <- coxme(Surv(age, status) ~ larvalTreat*adultTreat + strata(sex) +
                (1 | cageID), 
                data = eelife)
summary(cph2.3)
#car::Anova(cph2.3, type="III")
# cph2.2 and cph2.3 achieve same thing for additive terms only



anova(cxph1.2.1,cxph1.2.2,cph3)
nrow(cph3)


# To look at random treatment effects within center we can add a nested effect
cph3.1 <- coxme(Surv(age, status) ~ larvalTreat + adultTreat + sex +
                  (1 | cageID/larvalTreat), eelife)  
summary(cph3.1)

cph3.2 <- coxme(Surv(age, status) ~ larvalTreat + adultTreat + sex +
                  (1 | cageID/adultTreat), eelife)  
summary(cph3.2)

cph3.3 <- coxme(Surv(age, status) ~ larvalTreat + adultTreat + sex +
                  (1 | cageID/sex), eelife)  
summary(cph3.3)

cph3.4 <- coxme(Surv(age, status) ~ larv_adult + strata(sex) +
                  (1 | cageID/sex), eelife)  
summary(cph3.4)

# cph3.4 as it suggests that larval_adult diet combination affects trait
# In contrast, many models above consider effects of larval and adult diets in isolation.

```








