---
title: "Analysis and visualization of fecundity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cowplot)
library(colorblindr)
library(forcats)
library(ggpubr) # arrange plots
library(jtools) # for effect plots
library(ggstance) # additional functions for effect plots
library(sandwich) # additional functions for effect plots
library(broom.mixed)  # additional functions for effect plots

source("color_map.R")
source("ggplot_theme.R")
#source("color_map_blindr.R")

```

# Data

```{r}
eggs <- read.table("~/MyGithub/early_experience/processed/tricount.txt",
            sep = '\t', header = TRUE)

zdn <-eggs %>%  
  dplyr::select(id,age,cam_id,larvalTreat,adultTreat,
                NstartF,alive,aj1_count,aj2_count,dd1_count,numEggs,
                eggpDay,eggpFemDay)
head(zdn)

zdn %>% group_by(id) %>% summarise(sum(numEggs),n=n())
hist(log(zdn$numEggs))

```

# Lifetime group fecundity patterns
## Group by regime

```{r}

# Create regime column
zdn$Regime <- gsub("\\d", "", zdn$id)

# Mean fecundity for treatments at each age
fi <- group_by(zdn, age, Regime) %>% 
  summarise(Sum = sum(numEggs))
fi

# Overal mean fecundity for treatments
fii <-  group_by(zdn, Regime) %>%
  summarise(Mean = (numEggs))
fii

zz <- ggplot(fi, aes(x=Regime, y=Sum, color = Regime)) + 
  geom_jitter(size = 2, width=0.1, height=0.5) +
  #geom_point(data = fi, size = 4, shape = 0) +
  #geom_point(data = fif, size = 5, shape = 23) +
  labs(x = "Diet", 
       y = "log(Daily fecundity)", 
       color = "Regime") + 
  theme_half_open() +
  my_theme
zz


lt <- zdn %>% 
  ggplot(aes(x = age, y = log(numEggs), color = Regime, group = Regime)) +
  geom_jitter(alpha = 0.6) +
  geom_smooth(method='lm', formula= y~x, size=0.8) +
  scale_color_manual(values=c("#000000", "#E69F00", "#56B4E9", "#009E73")) + #"#F0E442", "#0072B2", "#D55E00", "#CC79A7")) +
 theme(legend.key.size = unit(0.5, 'cm'), 
        legend.key.height = unit(0.25, 'cm'), 
        legend.key.width = unit(0.5, 'cm'), 
        legend.title = element_text(size=11), 
        legend.text = element_text(size=8)) +
  labs(x = "Age (days)", y = "log(Lifetime fecundity") +
  theme_half_open() +
  my_theme
lt <- lt + theme(legend.position = c(0.7, 0.8))
    

# Diet effects on lifetime fecundity
ltime <-lm(log(numEggs) ~ Regime, data=zdn)
summary(ltime)
coef(ltime)
summary(ltime)$r.squared


ltp <- effect_plot(ltime, pred=Regime, interval=TRUE, 
                   int.type="confidence", int.width=0.95,
                   plot.points=TRUE, jitter = c(0.3,0), line.thickness=0.3,
                   point.alpha=0.2, y.label="log(Lifetime fecundity)",
                   x.label="Diet Regime",data=zdn)
ltp <- ltp + geom_point(color=c("#009E73","#56B4E9","#E69F00", "#000000")) + theme_half_open() + my_theme


lts <- plot_summs(ltime,inner_ci_level = .9,
                  plot.distributions = FALSE,
                  colors = 'grey')
lts <- lts + theme_half_open() + my_theme

#plot_coefs(ltime,inner_ci_level = .9)

ltf <- ggarrange(lt,ltp,lts, ncol = 3, nrow = 1, 
                 labels = c("a", "b","c"),
                 font.label = list(size = 10))
ggsave(ltf,file = "../plots/lifetime_fec_reg.pdf",
                width = 8,height=3)

# Add cage
ltimec <-lm(log(numEggs) ~ Regime + id, data=zdn)
summary(ltimec)

library(lme4)
library(report)
ltimecr <- lmer(log(numEggs) ~ Regime + (1|id), data = zdn)
summary(ltimecr)

report(ltimecr) %>% as.data.frame()
```

# Per female patterns
# Group by regime

```{r}
pp <- zdn %>% 
  ggplot(aes(x = age, y = log(eggpFemDay), color = Regime, group = Regime)) +
  geom_jitter(alpha = 0.6) +
  geom_smooth(method='lm', formula= y~x,size=0.8) +
  scale_color_manual(values=c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")) +
  # scale_colour_OkabeIto() +
  # tx_color_map() +
  #facet_grid(. ~ larvalTreat) +
  labs(x = "Age (days)", y = "log(Eggs/female/day)") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme

pp <-  pp + theme(legend.position = "none")

# Diet effects on per female fecundity
pff <-lm(log(eggpFemDay) ~ Regime, data=zdn)
summary(pff)
coef(pff)
summary(pff)$r.squared

# Plot effects
pffe <- effect_plot(pff, pred=Regime, interval=TRUE, 
                   int.type="confidence", int.width=0.95,
                   plot.points=TRUE, jitter = c(0.3,0), line.thickness=0.3,
                   point.alpha=0.2, y.label="log(Eggs/female/day)",
                   x.label="Diet Regime",data=zdn)
pffe <- pffe + geom_point(color=c("#009E73","#56B4E9","#E69F00", "#000000")) + theme_half_open() + my_theme

pffs <- plot_summs(pff,inner_ci_level = .9,
                  plot.distributions = FALSE,
                  colors = 'grey')
pffs <- pffs + theme_half_open() + my_theme


pfdf <- ggarrange(pp,pffe,pffs, ncol = 3, nrow = 1, 
                 labels = c("d", "e","f"),
                 font.label = list(size = 10))
ggsave(pfdf,file = "../plots/per_female_fec_reg.pdf",
                width = 8,height=3)

# Make panel
fec <- ggarrange(ltf,pfdf, ncol = 1, nrow = 2,
                 font.label = list(size = 10))
ggsave(fec,file = "../plots/fec_panel.pdf",
                width = 8,height=4)

pfec <-lmer(log(numEggs) ~ Regime + (1|id), data = zdn)
summary(pfec)
report(pfec) 
```

# Daily per female fecundity grouped by: 1) larval diet; 2) adult diet

```{r}

# Group by larval diet
aa <- zdn %>%
  ggplot(aes(x = age, y = log(eggpFemDay),
             color=larvalTreat, group_by(larvalTreat))) +
  geom_jitter(alpha = 0.6) +
  geom_smooth(size=0.8) +
  scale_color_manual(values=c("#000000", "#E69F00")) +
  # scale_colour_OkabeIto() +
  # tx_color_map() +
  #facet_grid(. ~ larvalTreat) +
  labs(x = "Age (days)", y = "log(Eggs/female/day)") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme

aa <- aa + theme(legend.position = "top")

# aam <-lm(log(eggpFemDay) ~ larvalTreat, data=zdn)
# summary(aam)
# 
# # aa <- aa + theme(
# #   #plot.title = element_blank(),
# #   axis.title.x = element_blank())
# 
# aame <- effect_plot(aam, pred=larvalTreat, interval=TRUE, 
#                    int.type="confidence", int.width=0.95,
#                    plot.points=TRUE, jitter = c(0.3,0), line.thickness=0.3,
#                    point.alpha=0.2, y.label="log(Eggs/female/day)",
#                    x.label="Diet Regime",data=zdn)
# aame <- aame + geom_point(color=c("#009E73","#56B4E9")) + theme_half_open() + my_theme
# 
# aams <- plot_summs(aam,inner_ci_level = .9,
#                   plot.distributions = FALSE,
#                   colors = 'grey')
# aams <- aams + theme_half_open() + my_theme
# 
# 
# aamf <- ggarrange(aa,aame,aams, ncol = 3, nrow = 1, 
#                  labels = c("g", "h","i"),
#                  font.label = list(size = 10))
# ggsave(aamf,file = "../plots/per_female_fec_larv.pdf",
#                 width = 8,height=2)
# 
# # Group by adult diet
bb <- zdn %>%
  ggplot(aes(x = age, y = log(eggpFemDay), color = adultTreat,
             group_by(adultTreat))) +
  geom_jitter(alpha = 0.6) +
  geom_smooth(size=0.8) +
  scale_color_manual(values=c("#000000", "#E69F00")) +
  # scale_colour_OkabeIto() +
  # tx_color_map() +
  #facet_grid(. ~ larvalTreat) +
  labs(x = "Age (days)", y = "log(Eggs/female/day)") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme

bb <- bb + theme(legend.position = "top")

# bb <- bb + theme(
#   strip.background = element_blank(),
#   strip.text.x = element_blank())
# 
# cc <- zdn %>% 
#   ggplot(aes(x = age, y = eggpFemDay, color = larvalTreat, group = Regime)) +
#   geom_jitter(alpha=0.6) +
#   geom_smooth(aes(group = larvalTreat), se = FALSE, color = "black",size=0.8) +
#   scale_color_manual(values=c("#999999", "#E69F00"),guide=FALSE) +
#   # scale_colour_OkabeIto() +
#   # tx_color_map() +
#   facet_grid(. ~ larvalTreat) +
#   labs(x = "Age (days)", y = "Eggs/female/day") +
#   #theme(legend.position = "none") +
#   theme_half_open() +
#   my_theme
# 
# cc <- cc + theme(strip.background = element_blank(),
#            strip.text.x = element_blank())
# 
# # On the same page
eggs <- ggarrange(aa,bb, ncol = 2, nrow = 1,
                 labels = c("g", "h"),
                 font.label = list(size = 10))

ggsave(eggs,file = "../plots/eggs_perFemale_perDay.pdf",
                width = 5,height=3)


```

# Relationship between lifespan and fecundity

```{r}
# Lifespan

quants <- read.csv("../processed/quantiles.csv")
#zdn$sgroup <- gsub("\\d", "", zdn$id)
#edata <- edata[order(edata$age),]

quants$X <- gsub("[a-z]", "", quants$X)
quants$X <- gsub("T=", "", quants$X)
quants$X <- gsub("=", "", quants$X)
quants$X <- gsub(", ", "_", quants$X)
quants$X <- gsub(" ", "", quants$X)

quants <- quants%>%
  rename(sgroup="X",
         q25="quantile.25",ci25l="lower.25",ci25h="upper.25",
         q50="quantile.50",ci50l="lower.50",ci50h="upper.50",
         q75="quantile.75",ci75l="lower.75",ci75h="upper.75") %>%
  unite("ci25",ci25l,ci25h,sep="-") %>%
  unite("ci50",ci50l,ci50h,sep="-") %>%
  unite("ci75",ci75l,ci75h,sep="-")

qfemale <- quants %>%
  filter(stringr::str_detect(sgroup, "_F"))

qfemale$Regime <- str_split(qfemale$sgroup, "_F", simplify = TRUE)[,1] 

qfemale <- dplyr::select(qfemale, Regime,q25,q50,q75) %>%
  pivot_longer(cols=2:4,names_to = "Quartile",values_to="surv_prob")

```

# Add all egg data to graph for summarized quants

```{r}
# Mean eggs per quantile
se = function(x) sd(x)/sqrt(length(x))

zdn$Regime <- gsub("\\d", "", zdn$id)
                            
quantile(zdn$age)


uq25 <- filter(zdn, age <= 20) %>%
  dplyr::select(Regime,age,eggpFemDay)
uq25$Quartile <- "q25"

uq25se <- uq25 %>%
  dplyr::select(Regime,age,eggpFemDay) %>%
  group_by(Regime) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq25se$Quartile <- "q25"


uq50 <- filter(zdn, age %in% (21:41)) %>%
  dplyr::select(Regime,age,eggpFemDay)
uq50$Quartile <- "q50"

uq50se <- uq50 %>%
  dplyr::select(Regime,age,eggpFemDay) %>%
  group_by(Regime) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq50se$Quartile <- "q50"


uq75 <- filter(zdn, age %in% (42:59)) %>%
  dplyr::select(Regime,age,eggpFemDay)
uq75$Quartile <- "q75"

uq75se <- uq75 %>%
  dplyr::select(Regime,age,eggpFemDay) %>%
  group_by(Regime) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq75se$Quartile <- "q75"


uq100 <- filter(zdn, age %in% (60:85)) %>%
  dplyr::select(Regime,age,eggpFemDay)
uq100$Quartile <- "q100"

uq100se <- uq100 %>%
  dplyr::select(Regime,age,eggpFemDay) %>%
  group_by(Regime) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
            qse = se(eggpFemDay))
uq100se$Quartile <- "q100"


uq <- rbind(uq25,uq50,uq75,uq100)
uqse <- rbind(uq25se,uq50se,uq75se,uq100se)


tf <- uq %>%
  arrange(age) %>%
  mutate(Quartile = factor(Quartile, levels=c("q25","q50","q75","q100"))) %>%
  group_by(Quartile) %>%
  ggplot(aes(age,eggpFemDay,color=Quartile)) +
  geom_jitter(size=3, alpha = 0.6) +
  geom_smooth(se=FALSE,color="black") +
  #geom = c("point", "line",data=uqse,aes(Regime,qe)) +
  #facet_grid(. ~ Regime) +
  facet_grid(cols=vars(Regime), rows=vars(Quartile), scales= "free_y") +
  scale_colour_OkabeIto() +
  #tx_color_map() +
  xlab("Age (Days)") + ylab("Eggs/female/day") +
  my_theme +
  theme_half_open() 
tf + labs(fill = "Quartile")

ggsave(tf,file = "../plots/Eggs_perFemale_Quartiles.pdf",
                width = 6,height=4)
ggsave(tf,file = "../plots/Eggs_perFemale_Quartile.pdf",
                width = 8,height=6)


# library(grid)
# grid.newpage()
# grid.draw(rbind(ggplotGrob(tv), ggplotGrob(tt), size = "last"))

```






