---
title: "Early Experience Factorial Experiment"
author: "Enoch Ng'oma"
date: "7/4/2018"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# Analysis of diet-dependent developmental plasticity in D. melanogaster lifespan

# Load packages

```{r}
library(survival)
library(survminer)
library(splines) #needed by survival package
library(tidyverse) 
library(forcats)
library(cowplot)
#library(coxme)
#library(brms)

source("color_map.R")
source("ggplot_theme.R")
```

## Load data & combine female and male events

```{r}
# Female data
eelifeF <- read.table('../processed/Female_events_eelife.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) 

# the diet combination column is tripped in the functions, recreate it
# eelifeF <- eelifeF %>%
#   unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)
eelifeF$sex <- "F"

# Male data
eelifeM <- read.table('../processed/Male_events_eelife.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) 

# the diet combination column is stripped in the functions, recreate it
# eelifeM <- eelifeM %>%
#   unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)
eelifeM$sex <- "M"
  
# Merge data
eelife <- bind_rows(eelifeF,eelifeM) %>% 
  select(-setDate, -flipDate, -age, -carriedM, -carriedF)

names(eelife)[1:2]<-c("age", "cageID")

#eelife$carried <- 0 
 
write.csv(eelife, file="../processed/eeAlldat.csv")
```

# Descriptives

```{r, dens}
cohort <- c('F&M','FF','MM')

dens.list <- vector(mode='list', length=3)
names(dens.list) <- cohort

for (ii in cohort) {
  
if(ii=='F&M')
{
# Male and female together

pp <- ggplot(eelife, aes(age, color = larv_adult)) + 
    geom_density(alpha = 0.5) +
    coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.03)) + 
    #adjust frame of x-axis
  
    scale_x_continuous(expand = c(0, 0), limits = c(-10, 120)) +
    expand_limits(x=125) +
    #limit plot area on x-axis
  
    scale_y_continuous(expand = c(0, 0)) +
    tx_color_map() +
    theme(axis.title = element_text(size = 12)) +
    xlab("Age (days)") +
    ylab("Density") +
    theme_half_open() +
    theme(legend.position = "none") 

    #element.text = 12
    #tx_fill_map() +
    #my_theme
#fm
}
  
if(ii=='FF')
  
{

# Female alone

pp <- ggplot(eelifeF, aes(age, color = larv_adult)) + 
    geom_density(alpha = 0.5) +
    coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.03)) + 
    #adjust frame of x-axis
    scale_x_continuous(expand = c(0, 0), limits = c(-10, 120)) +
    expand_limits(x=125) +
    #limit plot area on x-axis
    scale_y_continuous(expand = c(0, 0)) +
    tx_color_map() +
    theme(axis.title = element_text(size = 12)) +
    xlab("Age (days)") +
    ylab("Density") +
    theme_half_open() +
    theme(legend.position = "none") 
#ff

}
  
if(ii=='MM')

{
# Male alone

pp <- ggplot(eelifeM, aes(age, color = larv_adult)) + 
    geom_density(alpha = 0.5) +
    coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.03)) + 
    #adjust frame of x-axis
    scale_x_continuous(expand = c(0, 0), limits = c(-10, 120)) +
    expand_limits(x=125) +
    #limit plot area on x-axis
    scale_y_continuous(expand = c(0, 0)) +
    tx_color_map() +
    theme(axis.title = element_text(size = 12)) +
    xlab("Age (days)") +
    ylab("Density") +
    theme_half_open() +
    theme(legend.position = c(0.7, 0.8)) 
#mm
}
dens.list[[ii]] <- pp
}

densPlot <- plot_grid(dens.list[[1]],dens.list[[2]],dens.list[[3]],
                      nrow =3, ncol=1, 
                      labels = c('a.', 'b.', 'c.'), 
                      align = 'h', 
                      rel_widths = c(1.5,1.5, 1.5), 
                      label_size = 10)

ggsave(last_plot(), file = "../plots/density_all-life_data.pdf",
       width = 6, height = 4)
```

# Kaplan-Meier by diet plot with survminer

```{r}
# by treatment combinations
ee.comb <- survfit(Surv(age, status == 2) ~ larv_adult,
                   conf.type = "log", 
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
str(summary(ee.comb)$table)

# median for each treatment
summary(ee.comb)$table[, "median"]

# survival plot for treatment combinations
ee.comb_plot <- ggsurvplot(ee.comb, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Larval-Adult Diet") +
  xlab("Age (days)")
ee.comb_plot

#ggpar(ee.plot, axis.text = element_text(size = font_size),
      #font.x = c(font_size),
      #font.y = c(font_size),
      #font.tickslab = c(font_size))
#KM_plot <- last_plot()
#ggsave(last_plot(), file = "../../Figures/K-M_diet_summarized_survminer.pdf",
       #width = 4, height = 4)
#save(KM_plot, file = "../../Figures/KM_plot.Rda")



# survival by larval diet only
ee.larv <- survfit(Surv(age, status == 2) ~ larvalTreat,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
summary(ee.larv)$table

# median for each treatment
summary(ee.larv)$table[, "median"]

# survival
ee.larv_plot <- ggsurvplot(ee.larv, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Larval Diet") +
  xlab("Age (days)")
ee.larv_plot


# survival by adult diet only
ee.adul <- survfit(Surv(age, status == 2) ~ adultTreat,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
summary(ee.adul)$table

# median for each treatment
summary(ee.adul)$table[, "median"]

# survival
ee.adul_plot <- ggsurvplot(ee.adul, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Adult Diet") +
  xlab("Age (days)")
ee.adul_plot

# survival by line
ee.line <- survfit(Surv(age, status == 2) ~ cageID,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
summary(ee.line)$table

# median for each treatment
summary(ee.line)$table[, "median"]

# survival
ee.line_plot <- ggsurvplot(ee.line, data = eelife, 
                     conf.int = FALSE,
                     #palette = c("#999999", "#E69F00", 
                     #            "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Adult Diet") +
  xlab("Age (days)")
ee.line_plot
```

# Test differences

```{r testdiff}
test_all <- survdiff(Surv(NewAge, status == 2) ~ diet,
                     data = eelife, rho = 0) # log-rank (Mantel-Haenszel) test
test_all1 <- survdiff(Surv(NewAge, status == 2) ~ diet,
                      data = eelife, rho = 1) # Wilcoxon (Peto & Peto test)
test_all
test_all1

quantile(h2.diet,  probs = c(0.1, 0.5, 0.9))
```

# Pairwise tests

```{r}
test_pairwise <- pairwise_survdiff(
  Surv(age, status == 2) ~ diet, 
  data=eelife, p.adjust.method = "bonferroni", rho = 0)
test_pairwise1 <- pairwise_survdiff(
  Surv(NewAge, status == 2) ~ diet, 
  data=eelife, p.adjust.method = "bonferroni", rho = 1)

test_pairwise
test_pairwise1

# significance symbols
symnum(test_pairwise$p.value,
       cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
       symbols = c("****", "***", "**", "*", "+", " "),
       abbr.colnames = FALSE, na = "")

symnum(test_pairwise1$p.value,
       cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
       symbols = c("****", "***", "**", "*", "+", " "),
       abbr.colnames = FALSE, na = "")
```

# Reaction norms for sire families

```{r}
# remove censored events
h2rn_filtered <- eelife[eelife$status != 3, ] 

# prep each treatment into its own column

# pull HS and compute median
HS <- subset(h2rn_filtered, diet == "HS")
hs_trim <- cbind.data.frame(HS$sireid, HS$NewAge)
hs_med <- aggregate(. ~ HS$sireid, data = hs_trim, FUN = median)
hs_med[, 2] <- NULL
colnames(hs_med) <- c("sireid", "age")
hs_med$diet <- "HS"

# pull DR and compute median
DR <- subset(h2rn_filtered, diet == "DR")
dr_trim <- cbind.data.frame(DR$sireid, DR$NewAge)
dr_med <- aggregate(. ~ DR$sireid, data = dr_trim, FUN = median)
dr_med[, 2] <- NULL
colnames(dr_med) <- c("sireid", "age")
dr_med$diet <- "DR"

# pull C and compute median
C <- subset(h2rn_filtered, diet == "C")
c_trim <- cbind.data.frame(C$sireid, C$NewAge)
c_med <- aggregate(. ~ C$sireid, data = c_trim, FUN = median)
c_med[, 2] <- NULL
colnames(c_med) <- c("sireid", "age")
c_med$diet <- "C"

# Join data frames
mlife1 <- rbind(hs_med, c_med, dr_med)
mlife1 <- mlife1[!(mlife1$sireid=="S39"), ]

#reorder x-axis (ggplot default is alphabetical)
mlife1$diet <- as.character(mlife1$diet) #turn diet col into a char vector
mlife1$diet <- factor(mlife1$diet, levels = unique(mlife1$diet)) #back to ordered factor

# plot reaction norms for sire families
ggplot(mlife1, aes(x = diet, y = age, color = sireid)) +
  geom_point(size = 3) +
  geom_line(aes(group = sireid), alpha = 0.5, size = 1) +
  xlab("Diet") +
  ylab("Median lifespan (days)") +
  theme(legend.position = "none") +
  coord_cartesian(xlim = c(1.5, 2.5)) +
  my_theme
Lifespan_GxE <- last_plot()

ggsave(file = "../../Figures/eelife_reaction_norms.pdf",
       width = 4, height = 4)
save(Lifespan_GxE, file = "../../Figures/Lifespan_GxE.Rda")
```

