---
title: "Mixed effects Cox Regression"
author: "Enoch Ng'oma"
date: "7/4/2018"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options: 
  chunk_output_type: console
---

# Analysis of diet-dependent developmental plasticity in D. melanogaster lifespan

# Load packages

```{r}
library(survival)
library(coxme)
library(brms)
library(tidyverse) 
library(bayesplot)
library(broom)

#source("color_map.R")
#source("ggplot_theme.R")
```

## Load data & combine female and male events

```{r}

# Data has both male and female events

eelife <- read.csv("../processed/eeAlldat.csv")

```

# Basic model

age ~ larv + adult +sex + cluster(larv) : LarvalTreatDR becomes very sig

```{r}

M <- coxph(Surv(age, status==2) ~ larvalTreat + adultTreat + sex, 
                   data = eelife)
M

# Model with robust SE via clustering
M2 <- coxph(Surv(age, status==2) ~ larvalTreat + 
              adultTreat + sex + cluster(larvalTreat), data = eelife)
M2
``` 

# Mixed effects model

```{r}
M3 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat + 
              sex  + (1 | cageID), data = eelife)
M3

M4 <- coxme(Surv(age, status==2) ~ larvalTreat + sex  + 
              (1 | adultTreat), data = eelife)
M4

M5 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat + sex +
              (1 | cageID), data = eelife)
M5

M6 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat +
              (1 | sex), data = eelife)
M6

M7 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat +
              (1 | sex) + (1 | cageID), data = eelife)
M7
```


# Bayesian survival models


# rstanarm

```{r}
.rs.restartR()

suppressPackageStartupMessages()
library(rstanarm)
library(bayesplot)
library(dplyr)
library(ggplot2)
library(broom)

set.seed(245387)
iter = 2000
```

```{r}
#devtools::dev_mode(on=T)
library(rstanarm)

source("stan_surv.R")
eelife <- read.csv("../processed/eeAlldat.csv")

eelife <- eelife %>% 
  select(-X)

mod1 <- stan_surv(formula = Surv(age,status==2) ~ larvalTreat + adultTreat + 
                    sex,
                    status==2, 
                    data = eelife, 
                    chains = 4, 
                    cores = 2, 
                    seed = 234961, 
                    iter = 2000)




summary(stg1)
prior_summary(stg1)
pp_check(stg1, nreps=100)

#devtools::devmode(on=F)
```


# brms

```{r brm_models, cache=TRUE}
eelife <- read.csv("../processed/eeAlldat.csv")

eelife <- eelife %>% 
  select(-X) 

eelife$censored <- ifelse(eelife[,"status"] == 2, 1, 0)

  # filter(status == 2) %>% 
  # mutate(censored = 0)

bm2 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + 
             sex + (1 | cageID),data = eelife,family = weibull(),
           prior = c(set_prior("normal(0,5)", class = "b"),
                     set_prior("cauchy(0,2)", class = "sd")),
                     #set_prior("lkj(2)", class = "cor")),
           warmup = 1000, iter = 2000, chains = 4,
           control = list(adapt_delta = 0.95))
summary(bm2)
prior_summary(bm2)
pp_check(bm2, nreps=100)

if (FALSE) {
  # gamma(0.01, 0.01) shape by default
  # student_t(3, 4, 10) for intercept
  # student_t(3, 0, 10) for sd
  bm1 <- brm(age | cens(censored) ~ 1,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm2 <- brm(age | cens(censored) ~ adultTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm3 <- brm(age | cens(censored) ~ larvalTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(age | cens(censored) ~ lvadComb,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  
  #stop here
  bm3 <- brm(age | cens(censored) ~ diet + (1 | sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(age | cens(censored) ~ diet + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm5 <- brm(age | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm6 <- brm(age | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid) +
               (1 | diet:sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  loo_comp <- loo(bm1, bm2, bm3, bm4)
  model_wts <- model_weights(bm1, bm2, bm3, bm4)

  save(list = c("bm1", "bm2", "bm3", "bm4", "bm5", "bm6", "loo_comp", "model_wts"),
       file = "../Data/Processed/Surv_models_bayes.Rda")
}
```

```{r}
load("../../Data/Processed/Surv_models_bayes.Rda")

loo_comp
data.frame(weight = round(model_wts, 3))
```
