---
title: "Lifetime fecundity"
author: "Enoch Ng'oma"
date: "March 10, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

library(tidyverse) 
library(cowplot)
library(gplots)
library(gdata)
library(gtools)

source("color_map.R")
source("ggplot_theme.R")
```

# Fecundity data

```{r}
fec <- read.table('../processed/Early_Experience_Data_V1.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE)


```

# Lifetime fecundity

```{r}
ltime <- fec[,5:12]

ltime <- unite(ltime, "larad", larvalTreat, 
               adultTreat, sep = "_", remove=FALSE) %>%
  select(-deadFemale, -deadMale, -censored)

```

# Effect of larval treatment on fecundity

- Larval diet has effect (***, ncq)
- Some effect of cage (*, ncq2)
- DR_C combination increases fecundity (***,nqc3b)
- Larval DR has effect(**,nql1,nql3)
- Adult DR has some effect (*. nql2)
- Larval DR interacts with adult DR (**,nql4)
- Interaction disappears if adult diet included as main effect (nql5)

```{r}
nqc1 <- aov(numEggs ~ larad, data = ltime)
nqc2 <- aov(numEggs ~ larad + id, ddata = ltime)

plotmeans(numEggs ~ id, data = ltime)
plotmeans(numEggs ~ larad, data = ltime)

#interaction.plot(ltime$id,ltime$larad,ltime$numEggs)

nqc3 <- aov(numEggs ~ larad + id + larad:id, data = ltime)
nqc3b <- lm(numEggs ~ larad + id + larad:id, data = ltime)

summary(nqc1)
summary(nqc2)
summary(nqc3)
summary(nqc3b)


# Effect of larval diet
nql1 <- lm(numEggs ~ larvalTreat, data = ltime)
nql2 <- lm(numEggs ~ adultTreat, data = ltime)
nql3 <- lm(numEggs ~ larvalTreat + adultTreat, data = ltime)
nql4 <- lm(numEggs ~larvalTreat + larvalTreat:adultTreat, data = ltime)
nql5 <- lm(numEggs ~larvalTreat + adultTreat + 
             larvalTreat:adultTreat, data = ltime)

summary(nql1)
summary(nql2)
summary(nql3)
summary(nql4)
summary(nql5)

```

