---
title: "PerFemaleFecundity"
author: "Enoch Ng'oma"
date: "4/14/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(cowplot)
library(colorblindr)



source("ggplot_theme.R")
source("color_map_blindr.R")
```

# Look at data

```{r pressure, echo=FALSE}

# Andrew data 1
aj1 <- read.table("~/MyGithub/early_experience/processed/Early_Experience_Data_rechecked.txt",sep = "\t", header = TRUE,stringsAsFactors = FALSE)

which(is.na(aj1))
which(is.na(aj1$numEggs))
aj1[which(is.na(aj1$numEggs)),] 

# no eggs beyond age 77 days - remove rows
aj1 <- na.omit(aj1)

# Check duplicated camera_id
dup_ids <- which(duplicated(aj1$camera_id)) # 2 images dupl.
aj1[which(duplicated(aj1$camera_id)), ]

# Seems images 9834 (33 eggs) & 9835 15 eggs) are duplicated 
rbind(subset(aj1, aj1$camera_id=="9834") , 
            subset(aj1, aj1$camera_id=="9835"))

# For now, trash all 4
# aj1 <- aj1[which(!duplicated(aj1$camera_id)), ]


# Retain the first occurence of each
aj1 <- aj1[-c(189,190), ]
aj1 <- aj1[,c(2:3,5:8,10:12)]

# Recalculate age, then delete dates
aj1$startDate <- as.Date(aj1$startDate , "%m/%d/%y")
aj1$sampleDate <- as.Date(aj1$sampleDate , "%m/%d/%y")
aj1$age <- (aj1$sampleDate - aj1$startDate)
aj1$age <- as.numeric(aj1$age)
aj1 <- aj1 %>% 
  dplyr::select(-c(startDate,sampleDate))
aj1$id <- gsub("EE_","",aj1$id)

# Check re-counted images (original data was altered for new counts)
  # Original #s: IMG_9318 2491, IMG_9389-1136, and 9397-1461
  # Recounts:  9318-1043, 9389-645, and 9397-709

cam_id <- c("9318","9389","9397")
#new_count <- c(1043,645,709)

which(aj1$camera_id %in% cam_id)
aj1[c(22,30,38),]

# Percent censored - about 11%
sum(aj1$censored)
sum(aj1$deadFemale)
((sum(aj1$censored))/(sum(aj1$deadFemale)+sum(aj1$censored)))*100
# ~5% for each sex - ignore censored for per/female analysis

# Count females - dead and censored
sum(aj1$deadFemale)+sum(aj1$censored)

# Sum eggs in each replicate
cf_eggs <- aj1 %>%
  group_by(id) %>%
  summarise(sum(numEggs)) %>%
  pull() #output vector

# Check means per cage
scheck <- aj1 %>%
  group_by(id) %>%
  summarise(sum(numEggs), n=n())

# Number of dead females in a cage on each age
aj1$ndead <- aj1$deadFemale + aj1$censored
cf_dead <- aj1 %>%
  group_by(id) %>%
  summarise(sum(ndead)) %>%
  pull()
```

# Investigate 31 aj1 recounts - outliers

```{r}
recs <- read.csv("~/MyGithub/early_experience/processed/Recount_ImagesFlagged_extremeOutliers.csv")

names(recs)[1] <- "camera_id"
names(recs)[2] <- "numEggs"
recs$camera_id <- str_split(recs$camera_id, "_", simplify = TRUE)[,2]

aj1$camera_id <- as.character(aj1$camera_id)


llP <- left_join(recs, aj1, by="camera_id")
llP <- dplyr::select(llP,camera_id,numEggs.x,numEggs.y)
llP$dif <- ((llP$numEggs.x-llP$numEggs.y)/llP$numEggs.x)*100
llP <- llP[order(llP$camera_id),] 

# Use new numbers and repeat plotting

ffQ <- aj1 %>%
  dplyr::select(1:4,6:8)

ff <- subset(ffQ,ffQ$camera_id %in% recs$camera_id)
ff <- ff[order(ff$camera_id),] 
recs <- recs[order(recs$camera_id),] 

for(i in ff$camera_id) 
  if(i %in% recs$camera_id) 
    ff$numEggs[ff$numEggs <- recs$numEggs]

# Delete rows with old egg values
ffQ <- ffQ[!ffQ$camera_id %in% ff$camera_id, ]

#Check a few
ffQ[ffQ$camera_id== 9316,]

# Merge with the subset containing new values
ffQ <- ffQ[order(ffQ$camera_id),]
ffQ <- rbind(ffQ,ff)


# Check if values correctly replaced
#aj1 <- aj1[order(aj1$camera_id),] 
ffQ[ffQ$camera_id==9306,]
ffQ[ffQ$camera_id==9820,]

subset(ffQ,ffQ$camera_id %in% recs$camera_id)


```

# Integrate blind recounts

```{r}
# Masking file
mask <- read.table("~/MyGithub/early_experience/scripts/name_conversion.txt", 
                   header = FALSE)
colnames(mask) <- c("inum")
mask$rnum <- str_split(mask$inum, "-", simplify = TRUE)[,1] 
mask$itm <- str_split(mask$inum, "_", simplify = TRUE)[,2]
camera_id <- strsplit(mask$itm, ".", fixed = TRUE)
mask$camera_id <- unlist(lapply(camera_id, function(x) x[1]))

mask <- mask[order(mask$camera_id),]

recounts <- read.csv("~/MyGithub/early_experience/processed/recounts_checked.csv")

# Fix differing rownums
#subset(aj2, !(aj2$rnum %in% dd1$rnum))


nn <- ffQ[,c("camera_id","numEggs")]

which(!ffQ$camera_id %in% aj2$aj2_rnum)

all_equal(nn,aj2,dd1)
all_equal(nn,aj2,ignore_row_order = TRUE,convert = TRUE)
```

# Assign cf_start to each cage

```{r}
aj1$NstartF <- recode(aj1$id, 
                      "EE_C_C1" = cf_dead[1],
                      "EE_C_C2" = cf_dead[2],
                      "EE_C_DR1" = cf_dead[3],
                      "EE_C_DR2" = cf_dead[4],
                      "EE_DR_C1" = cf_dead[5],
                      "EE_DR_C2" = cf_dead[6],
                      "EE_DR_DR1" = cf_dead[7],
                      "EE_DR_DR2" = cf_dead[8])

```

# Calculate surviving females at each date

```{r}
ureps <- unique(aj1$id)

aj1$alive <- rep(NA, nrow(aj1))

aj1.t <- aj1[0,]

for(k in ureps) {
  aj1.s <- subset(aj1, id==k)
  for(i in 1:nrow(aj1.s)) {
    if(i == 1) {
      aj1.s[i,'alive'] <- aj1.s$NstartF[1]
    } else {
      if(is.na(aj1.s$deadFemale[i])) {
        aj1.s[i,'alive'] <- aj1.s[(i-1),'alive']
      } else {
        nDead <- aj1.s[i,'deadFemale']
        aj1.s[i,'alive'] <- aj1.s[(i-1),'alive']-nDead
      }
    }
  }
  aj1.t <- rbind(aj1.t, aj1.s)
}

aj1 <- aj1.t

min(aj1$alive,na.rm=TRUE)
which(is.na(aj1$alive))
aj1[which(aj1$alive<0),]
hist(aj1[which(aj1$alive<0),'alive'])

hist(aj1$alive)

# Per female per date fecundity
#aj1 <- aj1[,c(3:5,8:13)]
aj1$eggpDay <- aj1$numEggs*8
aj1$eggpFemDay <- aj1$eggpDay/aj1$alive

# Check that start values are assigned correctly
subset(aj1,aj1$id=="EE_DR_DR1") #176
subset(aj1,aj1$id=="EE_DR_DR2") #361
subset(aj1,aj1$id=="EE_DR_C1") #235
subset(aj1,aj1$id=="EE_DR_C2") #426
subset(aj1,aj1$id=="EE_C_C1") #190
subset(aj1,aj1$id=="EE_C_C2") #251
subset(aj1,aj1$id=="EE_C_DR1") #139
subset(aj1,aj1$id=="EE_C_DR2") #274

```

# Visualize

```{r}
# Collapse replicates
dat <- aj1 %>%
  unite(treat,larvalTreat,adultTreat,sep = "_",remove = TRUE,na.rm=TRUE) %>%
  unite(date_treat,age,treat,sep="_",remove=FALSE)
#dat <- dat[order(dat$age),]
names(dat)[3] <- "Treatment"

collapse.dat <- dat %>%
  group_by(treat, age) %>%
  summarise(mean_eggs = mean(eggpFemDay, na.rm = TRUE))

# Cage-wise
# collapse.dat <- dat %>%
#   group_by(Treatment, age) %>%
#   summarise(mean_eggs = mean(eggpFemDay, na.rm = TRUE))

collapse.dat <- collapse.dat[complete.cases(collapse.dat[,3]),]

# Plot overall eggs per female per 3-hr sampling period
pp <- ggplot(collapse.dat,aes(x=treat,y=mean_eggs, col=treat)) + 
  stat_boxplot(geom ='errorbar',width = 0.3) + 
  geom_boxplot() +
  geom_jitter() +
  scale_colour_OkabeIto() +
  xlab("Larval_Adult diet treatment") + 
  ylab("Mean eggs/Fem/date") +
  theme_half_open() +
  my_theme
pp + theme(legend.position = "none")

ggsave(pp, filename="~/MyGithub/early_experience/Plots/lifetime_eggs_perF_per3HR.pdf", height=4, width=4)

# Plot time series of eggs per female per 3-hr sampling period
qq <- ggplot(collapse.dat,aes(x=age,y=mean_eggs, col=treat)) +
  geom_line() +
  geom_point() +
  scale_colour_OkabeIto() +
  #scale_fill_OkabeIto() +
  xlab("Age (days)") + 
  ylab("Mean eggs/Fem/date") +
  theme_half_open() +
  my_theme
qq + theme(legend.position=c(0.7,1))

ggsave(qq, filename="~/MyGithub/early_experience/Plots/Eggs_perF_per3HR_timeseries.pdf", height=4, width=4)


# Plot time series of eggs per female per 3-hr sampling period
dat <- dat[complete.cases(dat[,c(3,5)]),]
tt <- ggplot(dat,aes(x=as.numeric(age),y=eggpFemDay, col=treat)) +
  geom_line() +
  geom_point() +
  scale_colour_OkabeIto() +
  #scale_fill_OkabeIto() +
  xlab("Age (days)") + 
  ylab("Eggs/♀/date") +
  theme_half_open() +
  my_theme
tt + theme(legend.position=c(0.4,1))

# Pull these lines and give these images a quick check
dat[which(dat$eggpFemDay>10),]
dat[which(dat$eggpFemDay<1 & dat$age<36),]

spot.check <- rbind(dat[which(dat$eggpFemDay>10),],dat[which(dat$eggpFemDay<1 & dat$age<36),])
```

# A faceted figure
```{r}
# Use facet_grid or facet_wrap to split up graphs by factors
ggplot(mydata, aes(Var1, Var2)) + geom_point() + facet_grid(~ Variety)
```


# Use new counts to see what changes

```{r}

```

# Reaction norms

```{r}
norms <- aj1[,c(4:5,15)]

# Calculate medians

# Get the four main treatments
richEarly <- subset(norms,larvalTreat=="C")
poorEarly <- subset(norms,larvalTreat=="DR")

# rich.rich <- subset(react,c(larvalTreat=="C" & adultTreat=="C"))

remed <- richEarly %>%
  group_by(adultTreat) %>%
  summarise(med_eggs = mean(eggpFemDay), n = n())
colnames(remed) <- c("adult", "mean_eggs", "N")
remed$grp <- "RichEarly"

pemed <- poorEarly %>%
  group_by(adultTreat) %>%
  summarise(med_eggs = mean(eggpFemDay), n = n())
colnames(pemed) <- c("adult", "mean_eggs", "N")
pemed$grp <- "PoorEarly"

med.all <- rbind(remed,pemed)

# Join data frames
med.all <- select(med.all, grp,adult,mean_eggs)

all.piv <- pivot_wider(med.all,
    names_from = adult,
    values_from = mean_eggs,
    values_fill = 0
    )

all.piv <- select(all.piv, grp,DR,C)

pdf("~/MyGithub/early_experience/plots/fec_norms.pdf",width=4, height=4)

par(mar=c(6,6,1,2.5))
matplot(t(all.piv[,2:3]),
        type='b',lty=1, lwd=2,pch=16,
        col = 1:6,
        ylab="Mean Eggs \n (3 hrs)",xlab="Adult Diet",
        axes=FALSE,cex.lab=1)
box()
axis(2,cex.axis=1.0)
axis(1, at=c(1,2), labels=c("DR","C"),cex.axis=1.0)

dev.off()
```

