---
title: "Fecundity models"
author: "Enoch Ng'oma"
date: "7/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lme4)
library(nlme)
library(cowplot)
library(colorblindr)
library(forcats)
library(ggrepel)
library(car)

source("color_map.R")
source("ggplot_theme.R")
```

# Data

```{r}
eggs <- read.table("~/MyGithub/early_experience/processed/tricount.txt",
            sep = '\t', header = TRUE)

zdn <- eggs %>% 
  dplyr::select(id,age,cam_id,larvalTreat,adultTreat,NstartF,alive,aj1_count,aj2_count,dd1_count,numEggs,
                eggpDay,eggpFemDay) %>%
  unite(treat,larvalTreat,adultTreat,sep = "_", remove = FALSE) 

head(zdn)

# Check for missing data
sum(!complete.cases(zdn))
```

# Eggs per female per day vs larval-adult diet treatment

```{r echo=FALSE}
set.seed(19)
ggplot(zdn, aes(eggpFemDay, treat, label = id)) +
  geom_point(size = 2) +
  geom_text_repel(size = 4, force = 15,
                  fontface = "italic",
                  box.padding = unit(0.5, "lines"),
                  point.padding = unit(0.5, "lines"),
                  arrow = arrow(length = unit(0.01, 'npc'))) +
  labs(x = "Eggs per female per day", 
       y = "Larval-adult treatment combination") +
  my_theme +
  theme_half_open() 
  
```

# Diet combi effects on per female fecundity

```{r}
zn1.0 <- lm(eggpFemDay ~ treat, data=zdn)
summary(zn1.0)
coef(zn1.0)
summary(zn1.0)$r.squared

# Use vial values instead of per female values
zn1.1 <- lm(numEggs ~ treat, data=zdn)
summary(zn1.1)
summary(zn1.1)$r.squared

# Plot diet combi data
ggplot(zdn, aes(treat, eggpFemDay, label = id)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", color = "grey", lwd = 1.5) +
  labs(x = "Larval-adult diet combination", 
       y = "No. of eggs per female per day") +
  theme_half_open() +
  my_theme

# Plot vial values instead of per female values
ggplot(zdn, aes(treat, numEggs, label = id)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", color = "grey", lwd = 1.5) +
  labs(x = "Larval-adult diet combination", 
       y = "No. of eggs over lifetime") +
  theme_half_open() +
  my_theme
```

# Add covariates

```{r}
## cage has no effect (i.e. substitute for id on the right)
## id dropped for further models

# Add age
zn2.0 <- lm(eggpFemDay ~ treat + age, data=zdn)
summary(zn2.0)
coef(zn2.0)
summary(zn2.0)$r.squared

# Add the interaction
zn2.1 <- lm(eggpFemDay ~ treat + age + treat:age, data=zdn)
summary(zn2.1)
coef(zn2.1)
summary(zn2.1)$r.squared
## DR_C diet combi interacts with age

# Extract and plot residuals of the interaction model
zdn$Res2.1 <- residuals(zn2.1)
zdn$Fitted <- fitted.values(zn2.1)

ggplot(zdn, aes(Fitted, Res2.1)) +
  geom_point() +
  geom_smooth() +
  geom_hline(yintercept=0,
             linetype="dashed",color = "red", size=1) +
  #facet_wrap("id", nrow = 4) +
  labs(x = "Fitted Values", y = "Residuals") +
  theme_half_open() +
  my_theme

# Check normality and homoscedasticity patterns
ggplot(zdn, aes(treat, Res2.1)) +
  geom_boxplot() +
  labs(x = "Diet combination", y = "Residuals")

ggplot(zdn, aes(sample=eggpFemDay))+
  geom_qq() + geom_qq_line()

ggplot(zdn, aes(sample = eggpFemDay)) +
  stat_qq(aes(color = id)) +
  #scale_color_manual(values = c("#00AFBB", "#E7B800"))+
  labs(y = "Eggs per female per day")
```

# Normalize with a weighted regression

```{r}
variance_struct <- varPower(form = ~ treat | age) # empty

zn2.2 <- gls(eggpFemDay ~ treat * age, data = zdn, 
           weights = variance_struct)

plot(zn2.2)

Anova(zn2.2, type = "III") # since model has interaction term

zdn$Res2.2 <- residuals(zn2.2, type = "normalized")

## Visualize of normalized model - scatter
ggplot(zdn, aes(treat, Res2.2)) +
  geom_jitter() +
  #facet_wrap("treat") +
  labs(x = "Diet combination",
       y = "Normalized residual (Eggs per female)")

## Visualize of normalized model - boxplot
ggplot(zdn, aes(treat, Res2.2)) +
  geom_violin() +
  geom_jitter() +
  ylim(c(-2, 8)) +
  labs(x = "Diet combination",
       y = "Normalized residual (Eggs per female)") +
  theme_half_open() +
  my_theme

as.data.frame(coef(zn2.2))
coef(zn2.2)
```







