---
title: "Fecundity Data"
author: "Andrew Jones"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(survival)
library(survminer)
library(splines) #needed by survival package
library(tidyverse) 
library(forcats)
library(cowplot)
#library(coxme)
#library(brms)

source("color_map.R")
source("ggplot_theme.R")
```

```{r}
eefecundity <- read.table("../Processed/Early_Experience_Data_V1.txt",
                          sep = "\t", stringsAsFactors = FALSE)


```

#Density
```{r}
ggplot(eefecundity, aes(numEggs, color = id)) + geom_density(alpha = 0.5) + coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.3))+ scale_x_continuous(expand = c(0, 0), limits = c(-10, 120)) + expand_limits(x=125) + scale_y_continuous(expand = c(0, 0)) + xlab("Fecundity") + ylab("Density") + theme(legend.position = c(0.7, 0.8))
                                                                                            
ggplot(eefecundity, aes(eefecundity$V12, color =eefecundity$V5))+
  geom_density(alpha = 0.5)+
  coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.3)) +
xlab("Fecundity") + 
 ylab("Density") +
  theme(legend.position = c(0.7, 0.8))
 
                                                                                            
                      
```

