---
title: "Fitness estimates using invasibility models"
author: "Enoch Ng'oma"
date: "10/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cowplot)
library(colorblindr)
library(forcats)
library(survival)
library(survminer)
library(demogR)

source("/Users/ngomae/MyGithub/Functions_and_Themes/ggplot_theme.R")

# Function to drop +0i from complex numbers
f <- function(x) {
   if (all(Im(z <- zapsmall(x))==0)) as.numeric(z) else x
}
```

# Data

```{r}

# Fecundity
eggs <- read.table("~/MyGithub/early_experience/processed/tricount.txt",
            sep = '\t', header = TRUE)

zdn <-eggs %>%  
  select(id,age,cam_id,larvalTreat,adultTreat,
                NstartF,alive,numEggs,eggpDay,eggpFemDay) %>%
  rename(cageID=id,larval=larvalTreat,adult=adultTreat)

zdn$Diet <- gsub("\\d", "", zdn$cageID)
tail(zdn)
zdn$age <- zdn$age +2 # we added 2 days to each row of lifespan (see InitialProcess.R)

# Collapse replicates
zdn$age <- as.numeric(zdn$age) 

lh <- zdn %>%
  arrange(cageID, age) %>%
  group_by(Diet,cageID) %>%
  mutate(snum = row_number()) %>% # specify flip#
  as.data.frame()

#lh$ad <- str_split(zdn$cageID, "_", simplify = TRUE)[,2]

lf <- lh %>%
  group_by(Diet,age) %>%
  summarize(n.eggs=mean(eggpFemDay),n=n()) %>%
  as.data.frame()

# Some ages are unmatched across regimes at the ends. Remove these to balance lengths, otherwise matrices will not form.

lf <- lf[!lf$age==73 & !lf$age==80 & !lf$age==85, ]
lf <- lf[!lf$age==87, ]


write.csv(lf,
          file = "~/MyGithub/early_experience/processed/eggDat_Leslie.csv",
          row.names = FALSE)


lf %>%
  group_by(Diet) %>%
  summarize(m.eggs=mean(n.eggs),n=n()) %>%
  as.data.frame()


# Lifespan
eelife <- read.csv("~/MyGithub/early_experience/processed/eeAlldat.csv") %>%
  select(-X,cageID,larv_adult,larvalTreat,adultTreat,age,status,sex) 

eelife$age <- as.numeric(eelife$age)
eelife$status <- as.numeric(eelife$status)

eelifeF <- eelife %>%
  filter(sex=="F")

# Survival data for best lifespan model
mf4_data <- survfit(Surv(age, status) ~ larv_adult + strata(sex), eelifeF)

surv4 <- mf4_data %>%
  surv_summary(data = eelifeF) %>%
  rename(age = time, Diet = larv_adult) %>%
  select(Diet, 1:3,5,) 

# Some ages are unmatched across regimes at the ends. Remove these to balance lengths, otherwise matrices will not form.
surv4 <- surv4[!surv4$age==73 & !surv4$age==82 & !surv4$age==85 & !surv4$age==87 & !surv4$age==89 ,]

# HL ends at age 75; add last row of zeros
# surv4 <- rbind(surv4, data.frame(Diet="HL",age=78, n.risk=0, n.event=0,surv=0))

write.csv(surv4,
          file = "~/MyGithub/early_experience/processed/survDat_bestModelF.csv",
          row.names = FALSE)


# Combine fecundity and lifespan

# X=age class, 
# Sx=survivors, 
# Dx= death events, 
# lx=survival to age x, 
# Tx=eggs per female per day
# mx=number of eggs per female in age class X

surv4$Diet <- as.character(surv4$Diet)  # Convert factor to character
lf$Diet <- as.character(lf$Diet)        # Ensure it's character

surv4 <- surv4 %>%
  mutate(Diet = recode(Diet, 
                       "HP_HP" = "HH",
                       "HP_LP" = "HL",
                       "LP_HP" = "LH",
                       "LP_LP" = "LL"))

surv_eggs <- inner_join(surv4, lf, by = c("Diet", "age"))  # Explicitly specify keys



write.csv(surv_eggs,
          file = "~/MyGithub/early_experience/processed/surv_eggs.csv",
          row.names = FALSE)

```

# Life tables

```{r}

surv_eggs <- read.csv("~/MyGithub/early_experience/processed/surv_eggs.csv") 

# Add row for zero mortality and fecundity before first age class
# Add row for zero survival and fecundity at the end of experiment

hh <- surv_eggs %>% filter(Diet=="HH") %>% 
  rename(count="n.risk",death="n.event",mx="n.eggs") %>% select(-n) 
hh <- rbind(data.frame(Diet="HH",age=0, count=426, death=0,surv=1,mx=0), hh)
hh <- rbind(hh, data.frame(Diet="HH",age=80, count=0, death=0,surv=0,mx=0))

hl <- surv_eggs %>% filter(Diet=="HL") %>% 
  rename(count="n.risk",death="n.event",mx="n.eggs") %>% select(-n) 
hl <- rbind(data.frame(Diet="HL",age=0, count=393, death=0,surv=1,mx=0), hl)
hl <- rbind(hl, data.frame(Diet="HL",age=80, count=0, death=0,surv=0,mx=0))

lh <- surv_eggs %>% filter(Diet=="LH") %>% 
  rename(count="n.risk",death="n.event",mx="n.eggs") %>% select(-n) 
lh <- rbind(data.frame(Diet="LH",age=0, count=625, death=0,surv=1,mx=0), lh)
lh <- rbind(lh, data.frame(Diet="LH",age=80, count=0, death=0,surv=0,mx=0))

ll <- surv_eggs %>% filter(Diet=="LL") %>% 
  rename(count="n.risk",death="n.event",mx="n.eggs") %>% 
  select(-n) 
ll <- rbind(data.frame(Diet="LL",age=0, count=510, death=0,surv=1,mx=0), ll)
ll <- rbind(ll, data.frame(Diet="LL",age=80, count=0, death=0,surv=0,mx=0))

# Life tables
hh.lt <- with(hh, life.table(x=age, nDx=death, nKx=count, type="cohort", iwidth=1, width12=c(1,1)))
hl.lt <- with(hl, life.table(x=age, nDx=death, nKx=count, type="cohort", iwidth=1, width12=c(1,1)))
lh.lt <- with(lh, life.table(x=age, nDx=death, nKx=count, type="cohort", iwidth=1, width12=c(1,1)))
ll.lt <- with(ll, life.table(x=age, nDx=death, nKx=count, type="cohort", iwidth=1, width12=c(1,1)))

# View function
#getAnywhere(life.table) # iwidth and width12!!!

```

# Create matices

```{r}
# nKx = mid-interval ppn str
# nLx = age-specific survival
# mx = age-specific fertility

hh.mx <- hh.lt %>% select(x,nLx) %>% rename(age="x") %>%  inner_join(hh) %>% select(1,3:7,2) 
hh.lmat <- leslie.matrix(lx=hh.mx$nLx, mx=hh.mx$mx)
hh.eig <- eigen.analysis(hh.lmat)

hl.mx <- hl.lt %>% select(x,nLx) %>% rename(age="x") %>%  inner_join(hl) %>% select(1,3:7,2) 
hl.lmat <- leslie.matrix(lx=hl.mx$nLx, mx=hl.mx$mx)
hl.eig <- eigen.analysis(hl.lmat)

lh.mx <- hh.lt %>% select(x,nLx) %>% rename(age="x") %>%  inner_join(lh) %>% select(1,3:7,2) 
lh.lmat <- leslie.matrix(lx=lh.mx$nLx, mx=lh.mx$mx)
lh.eig <- eigen.analysis(lh.lmat)

ll.mx <- hh.lt %>% select(x,nLx) %>% rename(age="x") %>%  inner_join(ll) %>% select(1,3:7,2) 
ll.lmat <- leslie.matrix(lx=ll.mx$nLx, mx=ll.mx$mx)
ll.eig <- eigen.analysis(ll.lmat)

# Plot sensitivities and elasticities
par(mfrow=c(3,4))
plot(hh.eig$sensitivities)
title("a")
plot(hl.eig$sensitivities)
title("b")
plot(lh.eig$sensitivities)
title("c")
plot(ll.eig$sensitivities)
title("d")

plot(hh.eig$elasticities)
title("e")
plot(hl.eig$elasticities)
title("f")
plot(lh.eig$elasticities)
title("g")
plot(ll.eig$elasticities)
title("h")

plot(hh.eig$repro.value)
title("i")
plot(hl.eig$repro.value)
title("j")
plot(lh.eig$repro.value)
title("k")
plot(ll.eig$repro.value)
title("l")

# Reproductive values
hh.age <- surv_eggs %>% filter(Diet=="HH") %>% select(age) 
hh.rv <- as.data.frame(cbind(hh.eig$stable.age,hh.eig$repro.value)) %>%
  rename(stable_age="V1", Rvalue="V2") %>%
  cbind(hh.age)

hhpl <- ggplot(hh.rv, aes(age,Rvalue)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Age (days)", y = "Reproductive value") +
  theme_half_open() +
  my_theme
hhpl <- hhpl + ggtitle("HH")

hl.age <- surv_eggs %>% filter(Diet=="HL") %>% select(age) 
hl.rv <- as.data.frame(cbind(hl.eig$stable.age,hl.eig$repro.value)) %>%
  rename(stable_age="V1", Rvalue="V2") %>%
  cbind(hl.age)

hlpl <- ggplot(hl.rv, aes(age,Rvalue)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Age (days)", y = "Reproductive value") +
  theme_half_open() +
  my_theme
hlpl <- hlpl + ggtitle("HL")
          
lh.age <- surv_eggs %>% filter(Diet=="LH") %>% select(age) 
lh.rv <- as.data.frame(cbind(lh.eig$stable.age,lh.eig$repro.value)) %>%
  rename(stable_age="V1", Rvalue="V2") %>%
  cbind(lh.age)

lhpl <- ggplot(lh.rv, aes(age,Rvalue)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Age (days)", y = "Reproductive value") +
  theme_half_open() +
  my_theme
lhpl <- lhpl + ggtitle("LH")
lhpl 

ll.age <- surv_eggs %>% filter(Diet=="LL") %>% select(age) 
ll.rv <- as.data.frame(cbind(ll.eig$stable.age,ll.eig$repro.value)) %>%
  rename(stable_age="V1", Rvalue="V2") %>%
  cbind(ll.age)

llpl <- ggplot(ll.rv, aes(age,Rvalue)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Age (days)", y = "Reproductive value") +
  theme_half_open() +
  my_theme
llpl <- llpl + ggtitle("LL")

library(ggpubr)
fitn <- ggarrange(hhpl,hlpl,lhpl,llpl, ncol = 2, nrow = 2, 
                 labels = c("a", "b","c","d"),
                 font.label=list(size=11,face="plain"))
fitn

ggsave(fitn,file = "~/MyGithub/early_experience/plots/leslie_fitness.pdf",
                width = 4,height=4.5)

c(hh.eig$lambda1,hh.eig$rho)
log(hh.eig$rho)
max(hh.eig$repro.value)
range(hh.eig$repro.value)
c(hh.age$age[5:12],hh.eig$repro.value)

c(hl.eig$lambda1,hl.eig$rho)
log(hl.eig$rho)
max(hl.eig$repro.value)
range(hl.eig$repro.value)

c(lh.eig$lambda1,lh.eig$rho)
log(lh.eig$rho)
max(lh.eig$repro.value)
range(lh.eig$repro.value)

c(ll.eig$lambda1,ll.eig$rho)
log(ll.eig$rho)
max(ll.eig$repro.value)
range(ll.eig$repro.value)

# ?eigen.analysis:
# lambda - asymptotic growth rate of a pop. (i.e. the dominant eigen val. of the matrix)
# rho - damping ratio (ratio of the dominant eigenvalue and the absolute value of the second eigenvalue)
# rho is a measure of the rate of convergence to the stable age-distribution. 
# rho is the rate by which the population will converge asymptotically to the stable age distribution exponentially with rate at least as fast as log(rho).
```

```{r}
# Assuming you have your eigenvalue lists for each treatment:
treatment_list <- list(hh = hh.eig, hl = hl.eig, lh = lh.eig, ll = ll.eig)

# Create a summary table
summary_table <- do.call(rbind, lapply(names(treatment_list), function(trt) {
  eig <- treatment_list[[trt]]
  data.frame(
    Treatment = trt,
    Lambda = eig$lambda1,
    MaxReproValue = max(eig$repro.value),
    MinReproValue = min(eig$repro.value),
    RangeReproValue = diff(range(eig$repro.value))
  )
}))

# View it
print(summary_table)

summary_table <- summary_table |> 
  mutate(across(where(is.numeric), \(x) round(x, 3)))


```

# Compare stable age distributions

```{r}

age <- hh.age
par(mfrow=c(2,2))
barplot(hh.eig$stable.age, names.arg=age, 
	     horiz=TRUE, 
	     col="grey", 
	     ylab="Age")

age <- hl.age
barplot(hl.eig$stable.age, names.arg=age, 
	     horiz=TRUE, 
	     col="blue", 
	     ylab="Age", 
	     xlim=c(0,0.2))

age <- lh.age
barplot(lh.eig$stable.age, names.arg=age, 
	     horiz=TRUE, 
	     col="blue", 
	     ylab="Age", 
	     xlim=c(0,0.2))

age <- ll.age
barplot(ll.eig$stable.age, names.arg=age, 
	     horiz=TRUE, 
	     col="blue", 
	     ylab="Age", 
	     xlim=c(0,0.2))
```


