---
title: "Early Experience lifespan brms"
author: "Enoch Ng'oma"
date: "7/4/2018"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) 
library(forcats)
library(cowplot)
#library(coxme)
library(brms)

source("color_map.R")
source("ggplot_theme.R")
```

# Data

```{r}
eelife <- read.csv("../processed/eeAlldat.csv")
```

# Bayesian survival models

```{r brm_models, cache=TRUE}
#library(brms)

eelife_2 <- eelife %>% 
  filter(status == 2) %>% 
  mutate(censored = 0)

if (FALSE) {
  # gamma(0.01, 0.01) shape by default
  # student_t(3, 4, 10) for intercept
  # student_t(3, 0, 10) for sd
  bm1 <- brm(NewAge | cens(censored) ~ 1,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm2 <- brm(NewAge | cens(censored) ~ adultTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm3 <- brm(NewAge | cens(censored) ~ larvalTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(NewAge | cens(censored) ~ lvadComb,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  
  #stop here
  bm3 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm5 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm6 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid) +
               (1 | diet:sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  loo_comp <- loo(bm1, bm2, bm3, bm4)
  model_wts <- model_weights(bm1, bm2, bm3, bm4)

  save(list = c("bm1", "bm2", "bm3", "bm4", "bm5", "bm6", "loo_comp", "model_wts"),
       file = "../Data/Processed/Surv_models_bayes.Rda")
}
```

```{r}
load("../../Data/Processed/Surv_models_bayes.Rda")

loo_comp
data.frame(weight = round(model_wts, 3))
```

```{r}
post <- posterior_samples(bm6)
STD <- post$b_Intercept
DR <- post$b_dietDR
HS <- post$b_dietHS

tibble(STD, DR = DR + STD, HS = HS + STD) %>% 
  gather(key = "Diet", value = "Posterior Estimate") %>% 
  ggplot(aes(`Posterior Estimate`, color = Diet)) +
  geom_line(stat = "density")

summary(bm6, prob = 0.99)
```

