---
title: "Analysis and visualization of fecundity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(cowplot)
library(colorblindr)
library(forcats)

source("color_map.R")
source("ggplot_theme.R")
#source("color_map_blindr.R")

```

```{r}
eggs <- read.table("~/MyGithub/early_experience/processed/tricount.txt",
            sep = '\t', header = TRUE)

zdn <-eggs %>%  
  select(id,age,cam_id,larvalTreat,adultTreat,
                NstartF,alive,aj1_count,aj2_count,dd1_count,numEggs,
                eggpDay,eggpFemDay)
head(zdn)
```

# Subset by 1) larval diet; 2) adult diet

```{r}
aa <- zdn %>% 
  ggplot(aes(x = age, y = eggpFemDay, color = larvalTreat, group = id)) +
  geom_line() +
  geom_smooth(aes(group = larvalTreat), se = FALSE, color = "black",size=0.8) +
  scale_color_manual(values=c("#999999", "#E69F00"),guide=FALSE) +
  # scale_colour_OkabeIto() +
  # tx_color_map() +
  facet_grid(. ~ larvalTreat) +
  labs(x = "Age (days)", y = "Eggs/female/3hrs") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme
aa <- aa + theme(
  plot.title = element_blank(),
  axis.title.x = element_blank())

bb <- zdn %>%
  ggplot(aes(x = age, y = eggpFemDay, color = adultTreat, group = id)) +
  geom_line() +
  geom_smooth(aes(group = adultTreat), se = FALSE, color = "black") +
  scale_color_manual(values=c("#999999", "#E69F00"),guide=FALSE) +
  #tx_color_map() +
  facet_grid(. ~ adultTreat) +
  labs(x = "Age (days)", y = "Eggs/female/3hrs") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme

bb <- bb + theme(
  plot.title = element_blank(),
  axis.title.x = element_blank())

bb <- bb + theme(strip.background = element_blank(),
           strip.text.x = element_blank())



# Subset by larval-adult diet combinations
zdn$tgroup <- gsub("\\d", "", zdn$id)

cc <- zdn %>% 
  ggplot(aes(x = age, y = eggpFemDay, color = larvalTreat, group = tgroup)) +
  geom_line() +
  geom_smooth(aes(group = larvalTreat), se = FALSE, color = "black",size=0.8) +
  scale_color_manual(values=c("#999999", "#E69F00"),guide=FALSE) +
  # scale_colour_OkabeIto() +
  # tx_color_map() +
  facet_grid(. ~ larvalTreat) +
  labs(x = "Age (days)", y = "Eggs/female/3hrs") +
  #theme(legend.position = "none") +
  theme_half_open() +
  my_theme

cc <- cc + theme(strip.background = element_blank(),
           strip.text.x = element_blank())

# On the same page
library(ggpubr)
eggs <- ggarrange(aa,bb,cc, ncol = 1, nrow = 3, 
                 labels = c("A", "B","C"))

ggsave(eggs,file = "../plots/eggs_perFemale_per3Hrs.pdf",
                width = 4,height=6)

```

# Relationship between lifespan and fecundity

```{r}
# Lifespan

quants <- read.csv("../processed/quantiles.csv")
#zdn$sgroup <- gsub("\\d", "", zdn$id)
#edata <- edata[order(edata$age),]

quants$X <- gsub("[a-z]", "", quants$X)
quants$X <- gsub("T=", "", quants$X)
quants$X <- gsub("=", "", quants$X)
quants$X <- gsub(", ", "_", quants$X)
quants$X <- gsub(" ", "", quants$X)

quants <- quants%>%
  rename(sgroup="X",
         q25="quantile.25",ci25l="lower.25",ci25h="upper.25",
         q50="quantile.50",ci50l="lower.50",ci50h="upper.50",
         q75="quantile.75",ci75l="lower.75",ci75h="upper.75") %>%
  unite("ci25",ci25l,ci25h,sep="-") %>%
  unite("ci50",ci50l,ci50h,sep="-") %>%
  unite("ci75",ci75l,ci75h,sep="-")

qfemale <- quants %>%
  filter(stringr::str_detect(sgroup, "_F"))

qfemale$tgroup <- str_split(qfemale$sgroup, "_F", simplify = TRUE)[,1] 

qfemale <- select(qfemale, tgroup,q25,q50,q75) %>%
  pivot_longer(cols=2:4,names_to = "phase",values_to="surv_prob")

# Mean eggs per quantile
zdn$tgroup <- gsub("\\d", "", zdn$id)

se = function(x) sd(x)/sqrt(length(x))
                            
quantile(zdn$age)

eggs_q25 <- filter(zdn, age <= 20) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q25_e = mean(eggpFemDay, na.rm = TRUE),
              q25_se = se(eggpFemDay))

eggs_q50 <- filter(zdn, age %in% (21:41)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q50_e = mean(eggpFemDay, na.rm = TRUE),
              q50_se = se(eggpFemDay))

eggs_q75 <- filter(zdn, age %in% (42:59)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q75_e = mean(eggpFemDay, na.rm = TRUE),
            q75_se = se(eggpFemDay))

# eggs_q100 <- filter(zdn, age %in% (60:85)) %>%
#   select(tgroup,age,eggpFemDay) %>%
#   group_by(tgroup) %>%
#   summarise(q100_e = mean(eggpFemDay, na.rm = TRUE),
#             q100_se = se(eggpFemDay))

eggsf <- Reduce(function(x, y) merge(x, y, all=TRUE), 
                    list(eggs_q25,eggs_q50,eggs_q75))
eggsf <- eggsf %>%
  pivot_longer(cols=-tgroup,
               names_to=c("qeggs_qse"),
               values_to="score") %>%
  as.data.frame() 


lu <- eggsf %>%
  filter(grepl("_se",qeggs_qse)) %>%
  rename(se_eggs="score")

le <- eggsf %>% 
  filter(grepl("_e",qeggs_qse)) %>%
  rename(eggs="score") %>%
  cbind(qfemale,lu) 
le <- le[,c(1,5,6,3,9)]


tv <- ggplot(le, aes(surv_prob,eggs),color=phase) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=eggs-se_eggs, ymax=eggs+se_eggs), width=.1,
                 position=position_dodge(0.05)) +
  facet_grid(. ~ tgroup) +
  #facet_grid(cols=vars(tgroup), rows=vars(phase), scales= "free_x") +
  #scale_x_discrete(position = "top") +
  #theme(axis.title.x = element_blank(), axis.text.x = element_blank())
  scale_colour_OkabeIto() +
  theme_half_open() 
  #tx_color_map() 
```

# Add all egg data to graph for summarized quants

```{r}
se = function(x) sd(x)/sqrt(length(x))

uq25 <- filter(zdn, age <= 20) %>%
  select(tgroup,age,eggpFemDay)
uq25$phase <- "q25"

uq25se <- uq25 %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq25se$phase <- "q25"


uq50 <- filter(zdn, age %in% (21:41)) %>%
  select(tgroup,age,eggpFemDay)
uq50$phase <- "q50"

uq50se <- uq50 %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq50se$phase <- "q50"


uq75 <- filter(zdn, age %in% (42:59)) %>%
  select(tgroup,age,eggpFemDay)
uq75$phase <- "q75"

uq75se <- uq75 %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
              qse = se(eggpFemDay))
uq75se$phase <- "q75"

uq100 <- filter(zdn, age %in% (60:85)) %>%
  select(tgroup,age,eggpFemDay)
uq100$phase <- "q100"

uq100se <- uq100 %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(qe = mean(eggpFemDay, na.rm = TRUE),
            qse = se(eggpFemDay))
uq100se$phase <- "q100"

uq <- rbind(uq25,uq50,uq75,uq100)
uqse <- rbind(uq25se,uq50se,uq75se,uq100se)

tf <- uq %>%
  arrange(age) %>%
  mutate(phase = factor(phase, levels=c("q25","q50","q75","q100"))) %>%
  group_by(phase) %>%
  ggplot(aes(age,eggpFemDay,color=tgroup)) +
  geom_jitter(size=3, alpha = 0.6) +
  geom_smooth(se=FALSE,color="black") +
  #geom = c("point", "line",data=uqse,aes(tgroup,qe)) +
  #facet_grid(. ~ tgroup) +
  facet_grid(cols=vars(tgroup), rows=vars(phase), scales= "free_y") +
  scale_colour_OkabeIto() +
  #tx_color_map() +
  my_theme +
  theme_half_open() 
tf

tf <- uq %>%
  group_by(phase)
  
qplot(age, eggpFemDay, geom = c("point", "line"),data=uq)

library(grid)
grid.newpage()
grid.draw(rbind(ggplotGrob(tv), ggplotGrob(tt), size = "last"))

```

# Median lifespan vs eggs

```{r}
head(qfemale)
qf <- filter(qfemale, phase=="q50")

head(zdn)
qs <- filter(zdn, age %in% (21:41)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q50_e = mean(eggpFemDay, na.rm = TRUE),
              q50_se = se(eggpFemDay))
```


```{r}
eggs_young <- filter(zdn, age <= quantile(zdn$age, probs = 0.25)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q25e = mean(eggpFemDay, na.rm = TRUE),
              q25se = se(eggpFemDay))
# se_young <- eggs_young[,c(1,3)]
# eggs_young <- select(eggs_young,tgroup,q25)



pyo <- ggplot(eggs_young,aes(tgroup,q25))+
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=q25-se_young,ymax=q25+se_young),
                width=.2,position=position_dodge(0.05)) +
  scale_colour_OkabeIto() +
  theme_half_open()


eggs_mid <- filter(zdn, age <= quantile(zdn$age, probs = 0.50)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q50e = mean(eggpFemDay, na.rm = TRUE),
              q50se = se(eggpFemDay))
se_mid <- eggs_mid[,c(1,3)]
eggs_mid <- select(eggs_mid,tgroup,q50)

pmid <- ggplot(eggs_mid,aes(tgroup,q50))+
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin=q50-std_err,ymax=q50+std_err),
                width=.2,position=position_dodge(0.05)) +
  scale_colour_OkabeIto() +
  theme_half_open() 


eggs_old <- filter(zdn, age <= quantile(zdn$age, probs = 0.75)) %>%
  select(tgroup,age,eggpFemDay) %>%
  group_by(tgroup) %>%
  summarise(q75e = mean(eggpFemDay, na.rm = TRUE),
            q75se = se(eggpFemDay))
# se_old <- eggs_old[,c(1,3)]
# eggs_old <- select(eggs_old,tgroup,q75)

pold <- ggplot(eggs_old,aes(tgroup,q75))+
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin=q75-std_err,ymax=q75+std_err),
                width=.2,position=position_dodge(0.05)) +
  scale_colour_OkabeIto() +
  theme_half_open()


library(ggpubr)
cir <- ggarrange(pyo, pmid, pold,ncol = 3, 
                 labels = c("a", "b", "c"))

ggplot2::ggsave(cir,file = "../../plots/transcripts_stat.pdf",
                width = 8,height=6)
```

