---
title: "Early Experience Factorial Experiment"
author: "Enoch Ng'oma"
date: "7/4/2018"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options: 
  chunk_output_type: console
---

# Analysis of diet-dependent developmental plasticity in D. melanogaster lifespan

# Load packages

```{r}
library(survival)
library(survminer)
library(splines) #needed by survival package
library(tidyverse) 
library(forcats)
library(cowplot)
#library(coxme)
#library(brms)

source("color_map.R")
source("ggplot_theme.R")
```

## Load data & combine female and male events

```{r}
# Female data
eelifeF <- read.table('../processed/Female_events_eelife.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) 

# the diet combination column is tripped in the functions, recreate it
# eelifeF <- eelifeF %>%
#   unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)
eelifeF$sex <- "F"

# Male data
eelifeM <- read.table('../processed/Male_events_eelife.txt',
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) 

# the diet combination column is stripped in the functions, recreate it
# eelifeM <- eelifeM %>%
#   unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)
eelifeM$sex <- "M"
  
# Merge data
eelife <- bind_rows(eelifeF,eelifeM) %>% 
  select(-setDate, -flipDate, -age)

names(eelife)[1:2]<-c("age", "cageID")

#eelife$carried <- 0 
  
#write.csv(eelife, file="../processed/eeAlldat.csv")
```

# Density

```{r, dens}
ggplot(eelife, aes(age, color = lvadComb)) + 
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(-10, 120), ylim = c(0, 0.03)) + 
  #adjust frame of x-axis
  
  scale_x_continuous(expand = c(0, 0), limits = c(-10, 120)) +
  expand_limits(x=125) +
  #limit plot area on x-axis
  
  scale_y_continuous(expand = c(0, 0)) +
  tx_color_map() +
  theme(axis.title = element_text(size = 12)) +
  xlab("Age (days)") +
  ylab("Density") +
  theme(legend.position = c(0.7, 0.8))
  #element.text = 12
  #tx_fill_map() +
  #my_theme

ggsave(last_plot(), file = "../Figures/density_all-life_data.pdf",
       width = 4, height = 4)
```

# Kaplan-Meier by diet plot with survminer

```{r}
# by treatment combinations
ee.comb <- survfit(Surv(NewAge, status == 2) ~ lvadComb,
                   conf.type = "log", 
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
str(summary(ee.comb)$table)

# median for each treatment
summary(ee.comb)$table[, "median"]

# survival plot for treatment combinations
ee.comb_plot <- ggsurvplot(ee.comb, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Larval-Adult Diet") +
  xlab("Age (days)")
ee.comb_plot

#ggpar(ee.plot, axis.text = element_text(size = font_size),
      #font.x = c(font_size),
      #font.y = c(font_size),
      #font.tickslab = c(font_size))
#KM_plot <- last_plot()
#ggsave(last_plot(), file = "../../Figures/K-M_diet_summarized_survminer.pdf",
       #width = 4, height = 4)
#save(KM_plot, file = "../../Figures/KM_plot.Rda")



# survival by larval diet only
ee.larv <- survfit(Surv(NewAge, status == 2) ~ larvalTreat,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
summary(ee.larv)$table

# median for each treatment
summary(ee.larv)$table[, "median"]

# survival
ee.larv_plot <- ggsurvplot(ee.larv, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Larval Diet") +
  xlab("Age (days)")
ee.larv_plot


# survival by adult diet only
ee.adul <- survfit(Surv(NewAge, status == 2) ~ adultTreat,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
# h2.diet
summary(ee.adul)$table

# median for each treatment
summary(ee.adul)$table[, "median"]

# survival
ee.adul_plot <- ggsurvplot(ee.adul, data = eelife, 
                     conf.int = FALSE,
                     palette = c("#999999", "#E69F00", 
                                 "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Adult Diet") +
  xlab("Age (days)")
ee.adul_plot

# survival by line
ee.line <- survfit(Surv(NewAge, status == 2) ~ id,
                   conf.int = 0.95,
                   type = "kaplan-meier",
                   error = "greenwood",
                   data = eelife)
summary(ee.line)$table

# median for each treatment
summary(ee.line)$table[, "median"]

# survival
ee.line_plot <- ggsurvplot(ee.line, data = eelife, 
                     conf.int = FALSE,
                     #palette = c("#999999", "#E69F00", 
                     #            "#56B4E9", "#009E73"),
                     fun = "pct", 
                     surv.median.line = "hv",
                     font.y = c(14),
                     risk.table = FALSE,
                     legend = c(0.9, 0.8),
                     #legend.labs = c("C", "DR", "HS"),
                     legend.title = "Adult Diet") +
  xlab("Age (days)")
ee.line_plot
```

# Bayesian survival models

```{r brm_models, cache=TRUE}
#library(brms)

eelife_2 <- eelife %>% 
  filter(status == 2) %>% 
  mutate(censored = 0)

if (FALSE) {
  # gamma(0.01, 0.01) shape by default
  # student_t(3, 4, 10) for intercept
  # student_t(3, 0, 10) for sd
  bm1 <- brm(NewAge | cens(censored) ~ 1,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm2 <- brm(NewAge | cens(censored) ~ adultTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm3 <- brm(NewAge | cens(censored) ~ larvalTreat,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(NewAge | cens(censored) ~ lvadComb,
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  
  #stop here
  bm3 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm5 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm6 <- brm(NewAge | cens(censored) ~ diet + (1 | sireid) + (1 | sireid:damid) +
               (1 | diet:sireid),
             data = eelife_2,
             family = weibull(),
             inits = "0",
             cores = 4)
  loo_comp <- loo(bm1, bm2, bm3, bm4)
  model_wts <- model_weights(bm1, bm2, bm3, bm4)

  save(list = c("bm1", "bm2", "bm3", "bm4", "bm5", "bm6", "loo_comp", "model_wts"),
       file = "../Data/Processed/Surv_models_bayes.Rda")
}
```

```{r}
load("../../Data/Processed/Surv_models_bayes.Rda")

loo_comp
data.frame(weight = round(model_wts, 3))
```
