---
title: "Mixed effects Cox Regression"
author: "Enoch Ng'oma"
date: "7/4/2018"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options: 
  chunk_output_type: console
---

# Analysis of diet-dependent developmental plasticity in D. melanogaster lifespan

# Load packages

```{r}
library(survival)
#library(coxme)
library(rstanarm)
library(brms)
library(tidyverse)
library(tidybayes)
library(bayesplot)
library(broom)

#source("color_map.R")
#source("ggplot_theme.R")
```

## Load data & combine female and male events

```{r}

# Data has both male and female events

eelife <- read.csv("../processed/eeAlldat.csv")

```

# Basic model

age ~ larv + adult +sex + cluster(larv) : LarvalTreatDR becomes very sig

```{r}

M <- coxph(Surv(age, status==2) ~ larvalTreat + adultTreat + sex, 
                   data = eelife)
M

# Model with robust SE via clustering
M2 <- coxph(Surv(age, status==2) ~ larvalTreat + 
              adultTreat + sex + cluster(larvalTreat), data = eelife)
M2
``` 

# Mixed effects model

```{r}
M3 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat + 
              sex  + (1 | cageID), data = eelife)
M3

M4 <- coxme(Surv(age, status==2) ~ larvalTreat + sex  + 
              (1 | adultTreat), data = eelife)
M4

M5 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat + sex +
              (1 | cageID), data = eelife)
M5

M6 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat +
              (1 | sex), data = eelife)
M6

M7 <- coxme(Surv(age, status==2) ~ larvalTreat + adultTreat +
              (1 | sex) + (1 | cageID), data = eelife)
M7
```


# Bayesian survival models

# rstanarm

```{r}

## Weibull
mod1 <- stan_surv(formula = Surv(age, status==2) ~ larvalTreat + 
                    adultTreat + sex, 
                  data    = eelife,
                  basehaz = "weibull",
                  chains  = 4, 
                  cores   = 4, 
                  seed    = 29,
                  iter    = 2000)

prior_summary(mod1)
summary(mod1)
print(mod1, digits = 3)

# Plot the baseline hazard function
plot(mod1) + coord_cartesian(ylim = c(0, 0.1))

tidybayes::tidy_draws(mod1)


# Gompertz
mod2 <- stan_surv(formula = Surv(age, status==2) ~ larvalTreat + 
                    adultTreat + sex, 
                  data    = eelife,
                  basehaz = "gompertz",
                  chains  = 4, 
                  cores   = 4, 
                  seed    = 29,
                  iter    = 2000)

summary(mod2)
print(mod2, digits = 3)

# Plot the baseline hazard function
plot(mod2) + coord_cartesian(ylim = c(0, 0.1))

tidybayes::tidy_draws(mod2)


# Cubic M-Spline - slower
mod3 <- stan_surv(formula = Surv(age, status==2) ~ larvalTreat + 
                    adultTreat + sex, 
                  data    = eelife,
                  basehaz = "ms",
                  chains  = 4, 
                  cores   = 4, 
                  seed    = 29,
                  iter    = 2000)

summary(mod3)
print(mod2, digits = 3)
plot(mod3) + coord_cartesian(ylim = c(0, 0.1))

tidybayes::tidy_draws(mod3)

## Cubic B-spline - quite slow!
mod4 <- stan_surv(formula = Surv(age, status==2) ~ larvalTreat + 
                    adultTreat + sex, 
                  data    = eelife,
                  basehaz = "bs",
                  chains  = 4, 
                  cores   = 4, 
                  seed    = 29,
                  iter    = 2000)

summary(mod4)
print(mod4, digits = 3)
plot(mod4) + coord_cartesian(ylim = c(0, 0.1))

tidybayes::tidy_draws(mod4)

# Exponential
mod5 <- stan_surv(formula = Surv(age, status==2) ~ larvalTreat + 
                    adultTreat + sex, 
                  data    = eelife,
                  basehaz = "exp",
                  chains  = 4, 
                  cores   = 4, 
                  seed    = 29,
                  iter    = 2000)

summary(mod5)
print(mod5, digits = 3)
plot(mod5) + coord_cartesian(ylim = c(0, 0.1))

tidybayes::tidy_draws(mod5)

# Baseline hazard function comparison

bayesplot::bayesplot_grid(plot(mod1),
                          plot(mod2),
                          plot(mod3),
                          plot(mod4),
                          ylim = c(-0.01, 0.15))

## Record execution time and multicore use
end_time <- Sys.time()
diff_time <- difftime(end_time, start_time, units = "auto")
cat("Started  ", as.character(start_time), "\n",
    "Finished ", as.character(end_time), "\n",
    "Time difference of ", diff_time, " ", attr(diff_time, "units"), "\n",
    "Used ", foreach::getDoParWorkers(), " cores\n",
    "Used ", foreach::getDoParName(), " as backend\n",
    sep = "")


# Compare the fit of models using `loo` method for stansurv objects
loo_compare(loo(mod1),
            loo(mod2),
            loo(mod3),
            loo(mod4))
```


# brms

```{r brm_models, cache=TRUE}
eelife <- read.csv("../processed/eeAlldat.csv")

eelife <- eelife %>% 
  select(-X) 

eelife$censored <- ifelse(eelife[,"status"] == 2, 1, 0)

  # filter(status == 2) %>% 
  # mutate(censored = 0)

bm2 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + 
             sex + (1 | cageID),data = eelife,family = weibull(),
           prior = c(set_prior("normal(0,5)", class = "b"),
                     set_prior("cauchy(0,2)", class = "sd"),
                     set_prior("lkj(2)", class = "cor")))

#################

# LKJ is shape parameter (ζ) of a symmetric beta distribution (implying correlations of zero) 

#  If ζ= 1 (the default in brms) the density is uniform over correlation matrices of the respective dimension. 

# If ζ >1, the identity matrix is the mode of the prior, with a sharper peak in the density for larger values of ζ. 

# If 0< ζ <1 the prior is U-shaped having a trough at the identity matrix, which leads to higher probabilities for non-zero correlations.  

###################

plot(bm2, ask = FALSE)
plot(conditional_effects(bm2), ask = FALSE)

summary(bm2)
prior_summary(bm2)
pp_check(bm2, nreps=100)

if (FALSE) {
  # gamma(0.01, 0.01) shape by default
  # student_t(3, 4, 10) for intercept
  # student_t(3, 0, 10) for sd
  bm1 <- brm(age | cens(censored) ~ 1,
             data = eelife,
             family = gaussian(),
             inits = "0",
             cores = 4)
  bm2 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + sex,
             data = eelife,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm3 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + 
               (1 | cageID),
             data = eelife,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm4 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + 
               (1 | larvalTreat : adultTreat),
             data = eelife,
             family = weibull(),
             inits = "0",
             cores = 4)
  bm5 <- brm(age | cens(censored) ~ larvalTreat + adultTreat + 
               (1 | larvalTreat : adultTreat) + (1 | cageID),
             data = eelife,
             family = weibull(),
             inits = "0",
             cores = 4)

  loo_comp <- loo(bm1, bm2, bm3, bm4, bm5)
  model_wts <- model_weights(bm1, bm2, bm3, bm4, bm5)

  save(list = c("bm1", "bm2", "bm3", "bm4", "bm5", 
                "loo_comp", "model_wts"),
       file = "../Data/Processed/Surv_models_bayes.Rda")
}
```

```{r}
load("../../Data/Processed/Surv_models_bayes.Rda")

loo_comp
data.frame(weight = round(model_wts, 3))
```
