---
title: "PerFemaleFecundity"
author: "Enoch Ng'oma"
date: "4/14/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(cowplot)
library(colorblindr)



source("ggplot_theme.R")
source("color_map_blindr.R")
```

# Look at data

```{r pressure, echo=FALSE}

fcd <- read.table("~/MyGithub/early_experience/processed/Early_Experience_Data_rechecked.txt",sep = "\t", header = TRUE,stringsAsFactors = FALSE)

fcd <- na.omit(fcd) 


# For now, trash duplicated image ids
fcd <- fcd[which(!duplicated(fcd$camera_id)), ]

fcd <- fcd[,c(2:3,5:8,10:12)]


# Recalculate age, then delete dates
fcd$startDate <- as.Date(fcd$startDate , "%m/%d/%y")
fcd$sampleDate <- as.Date(fcd$sampleDate , "%m/%d/%y")
fcd$age <- (fcd$sampleDate - fcd$startDate)
fcd$age <- as.numeric(fcd$age)

#fcd <- na.omit(fcd) 
#fcd <- fcd[!is.na(fcd$camera_id),]

# Check re-counted images
# Original #s: IMG_9318 2491, IMG_9389-1136, and 9397-1461
# Recounts:  9318-1043, 9389-645, and 9397-709

cam_id <- c("9318","9389","9397")
#new_count <- c(1043,645,709)

which(fcd$camera_id %in% cam_id)
fcd[c(22,30,38),]

# Percent censored - about 11%
sum(fcd$censored)
sum(fcd$deadFemale)
((sum(fcd$censored))/(sum(fcd$deadFemale)+sum(fcd$censored)))*100
# ~5% for each sex - ignore censored for per/female analysis

# Count females - dead and censored
sum(fcd$deadFemale)+sum(fcd$censored)

cf_eggs <- fcd %>%
  group_by(id) %>%
  summarise(sum(numEggs)) %>%
  pull() #output vector

# Check means per cage
scheck <- fcd %>%
  group_by(id) %>%
  summarise(mean(numEggs), n=n())

# Number of dead females in a cage on each age
fcd$ndead <- fcd$deadFemale + fcd$censored

cf_dead <- fcd %>%
  group_by(id) %>%
  summarise(sum(ndead)) %>%
  pull()
```

# Assign cf_start to each cage

```{r}
fcd$NstartF <- recode(fcd$id, 
                      "EE_C_C1" = cf_dead[1],
                      "EE_C_C2" = cf_dead[2],
                      "EE_C_DR1" = cf_dead[3],
                      "EE_C_DR2" = cf_dead[4],
                      "EE_DR_C1" = cf_dead[5],
                      "EE_DR_C2" = cf_dead[6],
                      "EE_DR_DR1" = cf_dead[7],
                      "EE_DR_DR2" = cf_dead[8])

```

# Calculate surviving females at each date

```{r}
ureps <- unique(fcd$id)

fcd$alive <- rep(NA, nrow(fcd))

fcd.t <- fcd[0,]

for(k in ureps) {
  fcd.s <- subset(fcd, id==k)
  for(i in 1:nrow(fcd.s)) {
    if(i == 1) {
      fcd.s[i,'alive'] <- fcd.s$NstartF[1]
    } else {
      if(is.na(fcd.s$deadFemale[i])) {
        fcd.s[i,'alive'] <- fcd.s[(i-1),'alive']
      } else {
        nDead <- fcd.s[i,'deadFemale']
        fcd.s[i,'alive'] <- fcd.s[(i-1),'alive']-nDead
      }
    }
  }
  fcd.t <- rbind(fcd.t, fcd.s)
}

fcd <- fcd.t

min(fcd$alive,na.rm=TRUE)
which(is.na(fcd$alive))
fcd[which(fcd$alive<0),]
hist(fcd[which(fcd$alive<0),'alive'])

hist(fcd$alive)

# Per female per date fecundity
fcd <- fcd[,c(3:8,11:12,14:15)]
fcd$eggpDay <- fcd$numEggs*8
fcd$eggpFemDay <- fcd$eggpDay/fcd$alive

# Check that start values are assigned correctly
# subset(fcd,fcd$id=="EE_DR_DR1") #176
# subset(fcd,fcd$id=="EE_DR_DR2") #361
# subset(fcd,fcd$id=="EE_DR_C1") #235
# subset(fcd,fcd$id=="EE_DR_C2") #426
# subset(fcd,fcd$id=="EE_C_C1") #190
# subset(fcd,fcd$id=="EE_C_C2") #251
# subset(fcd,fcd$id=="EE_C_DR1") #139
# subset(fcd,fcd$id=="EE_C_DR2") #274

```

# Visualize 

```{r}
# Collapse replicates
# dat <- fcd %>%
#   unite(treat,larvalTreat,adultTreat,sep = "_",remove = FALSE,na.rm=TRUE) %>%
#   unite(date_treat,age,treat,sep="_",remove=FALSE)
# #dat <- dat[order(dat$age),]
# names(dat)[5] <- "Treatment"

# Subset bt larval diet to assess theories (EM & SS)
fcd.poor <- fcd[c(fcd$larvalTreat=="DR"),]
fcd.rich <- fcd[c(fcd$larvalTreat=="C"),]

# Grouping by multiple variables
dat.poor <- fcd.poor %>%
  group_by(adultTreat, age) %>%
  dplyr::summarize(mean_eggs = mean(eggpFemDay, na.rm = TRUE))

dat.poor <- dat.poor[complete.cases(dat[,3]),]
dat.poor$adultTreat <- factor(dat.poor$adultTreat,
                              levels = c("DR", "C"))

# Plot overall eggs per female per 3-hr sampling period
pp <- ggplot(dat.poor,aes(x=adultTreat,y=mean_eggs, col=adultTreat)) + 
  stat_boxplot(geom ='errorbar',width = 0.3) + 
  geom_boxplot() +
  geom_jitter() +
  scale_colour_OkabeIto() +
  xlab("Poor larval diet (DR)") + 
  ylab("Mean eggs/Fem/date") +
  theme_half_open() +
  my_theme
pp + theme(legend.position = "none")

ggsave(pp, filename="~/MyGithub/early_experience/Plots/lifetime_eggs_perF_per3HR.pdf", height=5, width=10)

# Plot time series of eggs per female per 3-hr sampling period
qq <- ggplot(dat.poor,aes(x=age,y=mean_eggs, col=adultTreat)) +
  geom_smooth(method = lm, formula = y~x,se=FALSE) +
  geom_point() +
  scale_colour_OkabeIto() +
  #scale_fill_OkabeIto() +
  xlab("DR larval diet, Age (days)") + 
  ylab("Mean eggs/Fem/date") +
  theme_half_open() +
  my_theme
qq + theme(legend.position=c(0.7,1))

ggsave(qq, filename="~/MyGithub/early_experience/Plots/Eggs_perF_per3HR_timeseries.pdf", height=5, width=10)


# Plot on a numeric (0/1) diet treat
dat.poor[,"ntreat"] <- ifelse(dat.poor[,"adultTreat"]=="C",1,2) 


rr <- ggplot(dat.poor,aes(x=ntreat,y=mean_eggs, col=adultTreat)) +
  stat_summary(fun = 'mean',geom = 'point') +
  #stat_smooth(method = lm, formula = y~x,se=FALSE) +
  #geom_smooth(method = lm, formula = y~x,se=FALSE) +
  geom_line() +
  scale_colour_OkabeIto() +
  #scale_fill_OkabeIto() +
  xlab("DR larval diet, Age (days)") + 
  ylab("Mean eggs/Fem/date") +
  theme_half_open() +
  my_theme
rr + theme(legend.position=c(0.7,1))

ggplot(data, aes(x = Length, y= ReadT, colour = Pos)) + 
 stat_summary(fun.y = 'mean', geom = 'point')+
 stat_smooth(method = 'lm', aes(x=as.numeric(Length)), se = FALSE) +
 facet_grid(~Group)
```



