---
title: "NewCountComparisons"
author: "Andrew Jones"
date: "8/20/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(car)
library(MASS)
library(tidyverse)
library(cowplot)
library(ggpubr)
library(data.table)
```


## Getting Name Conversion
```{r pressure, echo=FALSE}
Random <- read.table("~/MyGithub/early_experience/scripts/name_conversion.txt", header = FALSE,stringsAsFactors = FALSE)
```

#Setting Up Randomized Table 
```{r}
split <- strsplit(Random$V1, "-")

head(split)

Organized <- data.frame(matrix(unlist(split), ncol = 2, byrow = TRUE))

colnames(Organized) <- c("Number", "Image_id")
 Organized$Number <-  as.numeric(Organized$Number)
 
 Ordered <- Organized[order(Organized[,1]),]
 
 row.names(Ordered) <- c(1:280)
```


#Integrating Two New Tables
```{r}
CountsAJ <- read.table("~/early_experience/original/ee_temp_Values_Sheet_AJ.txt", header = FALSE,stringsAsFactors = FALSE)

colnames(CountsAJ) <- c("Number", "Count")

CountsDD <- read.table("~/early_experience/original/EE_counts_DD.txt", header = FALSE,stringsAsFactors = FALSE)

colnames(CountsDD) <- c("Number", "Count")

CombinedAJ <- left_join(Ordered, CountsAJ, by = NULL, copy = FALSE)
CombinedAJ <- CombinedAJ %>% 
  mutate(Image_id = sub('IMG_', '', Image_id))
CombinedAJ <- CombinedAJ %>% 
  mutate(Image_id = sub('.JPG', '', Image_id))
CombinedDD <- left_join(Ordered, CountsDD, by = NULL, copy = FALSE)
CombinedDD <- CombinedDD %>% 
  mutate(Image_id = sub('IMG_', '', Image_id))
CombinedDD <- CombinedDD %>% 
  mutate(Image_id = sub('.JPG', '', Image_id))

CombinedAJ$Image_id <-  as.numeric(CombinedAJ$Image_id)
CombinedDD$Image_id <-  as.numeric(CombinedDD$Image_id)
```

#Adding the Combined to the other variables
```{r}
eeFec <- read.table("../processed/Early_Experience_LiFec.txt",
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE) 
fec <- eeFec[,c(4:7,11)]
colnames(fec) <- c("Age", "id", "larvalTreat", "adultTreat", "Image_id")
fec <- fec %>% 
  mutate(id = sub('EE_', '', id))
fec <- fec[,c(1:5)]

FullAJ <- left_join(fec, CombinedAJ, by = NULL, copy = FALSE)
FullAJ <- FullAJ[,c(1:5,7)]
FullAJ <- na.omit(FullAJ)
FullAJ <- FullAJ %>%
  unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)

FullDD <- left_join(fec, CombinedDD, by = NULL, copy = FALSE)
FullDD <- FullDD[,c(1:5,7)]
FullDD <- na.omit(FullDD)
FullDD <- FullDD %>%
  unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)

```

#Graphing
```{r}
ggplot(FullAJ, aes(Count, color = lvadComb)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(-10, 620), ylim = c(0, 0.013)) +
  labs(x = "Eggs", y = "Density", color = "Diet Combination", title = "AJ Density")

ggplot(FullDD, aes(Count, color = lvadComb)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(-10, 750), ylim = c(0, 0.013)) +
  labs(x = "Eggs", y = "Density", color = "Diet Combination", title = "DD Density")

ggplot(FullAJ, aes(Age, Count, color = lvadComb)) +
  geom_line() +
  coord_cartesian(xlim = c(-5, 60), ylim = c(0, 1200)) +
  geom_smooth() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "AJ Counts")

ggplot(FullDD, aes(Age, Count, color = lvadComb)) +
  geom_line() +
  coord_cartesian(xlim = c(-5, 60), ylim = c(0, 1200)) +
  geom_smooth() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "DD Counts")
  

ggplot(FullAJ, aes(Age, Count, color = lvadComb)) +
  geom_point() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "AJ Counts")
  

ggplot(FullDD, aes(Age, Count, color = lvadComb)) +
  geom_point() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "DD Counts")
  

ggplot(FullAJ, aes(x = lvadComb,y = Count, color = id))+
  geom_boxplot(alpha = 0.5) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "AJ Diets")
  

ggplot(FullDD, aes(x = lvadComb,y = Count, color = id))+
  geom_boxplot(alpha = 0.5) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "DD Diets")

ggplot(FullAJ, aes(x = Age, y = Count, color = lvadComb)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "AJ Line")

ggplot(FullDD, aes(x = Age, y = Count, color = lvadComb)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "DD Line")

ggplot(FullAJ, aes(x = lvadComb, y = Count, color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.1) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "AJ Point")

ggplot(FullAJ, aes(x = lvadComb, y = log(Count), color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.05) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "AJ Log Point")

ggplot(FullDD, aes(x = lvadComb, y = Count, color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.04) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "DD Point")

ggplot(FullDD, aes(x = lvadComb, y = log(Count), color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.03) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "DD Log Point")

ggplot(FullAJ, aes(x = lvadComb, y = Count, color = lvadComb)) +
  geom_violin() +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "AJ Violin")

ggplot(FullDD, aes(x = lvadComb, y = Count, color = lvadComb)) +
  geom_violin() +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "DD Violin")
```

#Getting Mean of All Three Tables
```{r}
Rechecked <- read.table("../processed/Early_Experience_Data_rechecked.txt",
                     sep = "\t", header = TRUE,
                     stringsAsFactors = FALSE)
Rechecked <- Rechecked[,c(4:7,11:12)]
colnames(Rechecked) <- c("Age", "id", "larvalTreat", "adultTreat", "Image_id", "Count")
Rechecked <- Rechecked %>% 
  mutate(id = sub('EE_', '', id))
Rechecked <- Rechecked %>%
  unite(lvadComb, larvalTreat, adultTreat, sep = "_", remove = FALSE)

Test1 <- merge(Rechecked, merge(FullAJ, FullDD, by = "Image_id"), by = "Image_id")


CombinedFull <- Test1[,c(1:7,13,19)]

colnames(CombinedFull) <- c("Image_id", "Age", "id", "lvadComb", "larvalTreat", "adultTreat", "Count_Rechecked", "Count_AJ", "Count_DD")

CombinedFull$Mean <- rowMeans(CombinedFull[,7:9])


```

#Graphing Mean
```{r}
ggplot(CombinedFull, aes(Mean, color = lvadComb)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(-10, 620), ylim = c(0, 0.011)) +
  labs(x = "Eggs", y = "Density", color = "Diet Combination", title = "Mean Density")

ggplot(CombinedFull, aes(Age, Mean, color = lvadComb)) +
  geom_line() +
  coord_cartesian(xlim = c(-5, 60), ylim = c(0, 1250)) +
  geom_smooth() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "Mean Counts")

ggplot(CombinedFull, aes(Age, Mean, color = lvadComb)) +
  geom_point() +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "Mean Counts")

ggplot(CombinedFull, aes(x = lvadComb,y = Mean, color = id))+
  geom_boxplot(alpha = 0.5) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "Mean Diets")
  
ggplot(CombinedFull, aes(x = Age, y = Mean, color = lvadComb)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  labs(x = "Age (Days)", y = "Eggs", color = "Diet Combination", title = "Mean Line")

ggplot(CombinedFull, aes(x = Age, y = log(Mean), color = lvadComb, shape = lvadComb)) +
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  coord_cartesian(xlim = c(0, 57), ylim = c(1, 7)) +
  labs(x = "Age (Days)", y = "(Log)Fecundity", color = "Diet Combination", shape = "Diet Combination", title = "Logarithmic Number of Eggs vs. Age(Days)") +
  theme_half_open()

testaov <- aov(log(Mean) ~ lvadComb, data = CombinedFull)
summary(testaov)
  

ggplot(CombinedFull, aes(x = lvadComb, y = Mean, color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.1) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "Mean Point")

ggplot(CombinedFull, aes(x = lvadComb, y = log(Mean), color = lvadComb)) +
  geom_point() +
  geom_jitter(width = 0.05) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "Mean Log Point")

ggplot(CombinedFull, aes(x = lvadComb, y = Mean, color = lvadComb)) +
  geom_violin() +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "Mean Violin")

ggplot(CombinedFull, aes(x = lvadComb,y = Mean, color = lvadComb))+
  geom_boxplot(alpha = 0.5) +
  labs(x = "Diet Combination", y = "Eggs", color = "Diet Combination", title = "Mean Diets")
```



